### ISSUE TITLE
[Q] eitinject already changes the SDT table ?

### ISSUE THREAD

**Issue by Litrona** [tsduck/tsduck#1004]
Do I need to change SDT eit flags to 1 manually, when I use -P eitinject ?
EIT_present_following_flag = 1 and EIT_schedule_flag = 1
I didn't find it in the manual.

Thanks

**Comment by lelegard** [comment]
Hi @Litrona 

This must be done separately. TSDuck is a low-level toolkit. All tasks which can be performed separately are handled in independent plugins. The plugin `eitinject` injects EIT's and that's all. To set the EIT indicators in the SDT, use the plugin `-P sdt --service-id XXX --eit-pf 1 --eit-schedule 1`. Add one such plugin for each service you want to update.

**Comment by Litrona** [comment]
OK, understood then. 
Thanks
