### ISSUE TITLE
error while loading shared libraries: libsrt.so.1.4:

### ISSUE THREAD

**Issue by Simon-Steinmann** [tsduck/tsduck#1014]
#### Bug description:
I installed tsduck on ubuntu 20.04using the binary from here [](https://tsduck.io/download/tsduck/). Executing `tsversion --check` in the terminal gives me this error:
`tsversion: error while loading shared libraries: libsrt.so.1.4: cannot open shared object file: No such file or directory`

#### Attempts to fix the issue:
[](https://github.com/tsduck/tsduck/issues/1003) as suggested in this post, I ran the install-prerequisites.sh file [](https://github.com/tsduck/tsduck/blob/master/scripts/install-prerequisites.sh). I reinstalled tsduck. The issue was still the same.

I also looked in /usr/lib and searched for libsrt, which gives me this result:
![image](https://user-images.githubusercontent.com/52213164/172661606-03938f95-e605-4b28-888b-68902c507577.png)

I tried installing` sudo apt install libsrt1.4-openssl`, but it gave me this error:
```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libsrt1.4-openssl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libsrt1.4-openssl' has no installation candidate
```

#### Environment:
 - OS: Linux 
 - OS version: Ubuntu 20.04.4 LTS 
 - TSDuck full version: 3.30-2710.ubuntu21
 - Installation type: binary tsduck_3.30-2710.ubuntu21_amd64.deb

**Comment by lelegard** [comment]
Hi @Simon-Steinmann 

The tsduck package you use was built for Ubuntu 21 (it's in its file name) and you have Ubuntu 20.04.

If I remember correctly, there was an ABI change and name change for the libsrt packages around Ubuntu 20. So, this tsduck package will not work on Ubuntu 20.

If you are stuck with Ubuntu 20, you need to rebuild a tsduck package from source on your system. This is [explained here](https://tsduck.io/doxy/building.html). This is quite simple. Just run `scripts/install-prerequisites.sh` the first time (this installs the required tools and libraries to build tsduck) and then `make installer`. You will get a fresh `.deb` file in subdirectory `installers`.

Note that TSDuck is prebuilt on the latest version of each distro. The next version will be built on Ubuntu 22. If you use older versions of the distro, you need to rebuild.
