### ISSUE TITLE
[Q] How to show CC errors in log?

### ISSUE THREAD

**Issue by barhom** [tsduck/tsduck#1015]
Question 1)
I run tsduck with input srt and output ip/udp like this;

`
tsp -v --debug -I srt --statistics-interval 10000 --listener XXXXX:10021 -O ip 239.100.0.17:1234
`
However, I would like it to show me a log in stdout whenever there is a CC error, how do I do that?

Question2)
I keep seeing the following in the log,
`* srt: unknown initial input bitrate`
What does this mean and what do I do to fix it?

**Comment by lelegard** [comment]
Hi @barhom 

> I would like it to show me a log in stdout whenever there is a CC error,

Did you try the `continuity` plugin? More generally, please have a look at the TSDuck user's guide and, when you need something, browse the list of commands and plugins.

> `* srt: unknown initial input bitrate`
> What does this mean and what do I do to fix it?

During the initial phase, `tsp` tries to evaluate the input bitrate from PCR in the first load (8 MB by default). If there is no or not enough PCR's in this initial load, you get this message in verbose mode (`tsp -v`). There is nothing to fix, this is just a verbose-level informational message.

**Comment by barhom** [comment]
Thank you
