### ISSUE TITLE
Changing Descriptor value for a TS on the fly 

### ISSUE THREAD

**Issue by Jazzykool85** [tsduck/tsduck#1022]
Dear Thierry,

I have this requirement of having a single TS stream with a descriptor on the NIT changed during the duration of the stream.
For instance
Stream1. TS 
Duration:- 10 mins
T0 :- NIT linkage descriptor is pointing to one ONID/TSID (currently on air)
T0 + 5mins :- NIT  linkage descriptor is pointing to another ONID/TSID 

What is the best way to achieve this using TSDuck,  I am having Stream1.TS currently with the  on air NIT linkage descriptor .
I am planning to use the Merge plugin for TSP  and trying to combine 2 TS files , One with default linkage and another with the change. Is this approach OK or do you think there is a better way.
Many thanks for your answer in advance 
Regards
Jazeem

**Comment by lelegard** [comment]
Hi @Jazzykool85 

I recommend to use the `inject` plugin with the `--poll-files` option. You prepare two XML or binary files for the NIT, one in the original format and one with the modification (do not forget to update the version number). 

After the given time, have some automated script replace the first XML file with the second one. The `inject` plugin will detect the modification of the file and inject the new NIT instead of the previous one.

**Comment by Jazzykool85** [comment]
Hi @lelegard ,
I think am getting something wrong with this one.
how can i achieve this ?
After the given time, have some automated script replace the first XML file with the second one.
Need to be sure.Thanks

**Comment by lelegard** [comment]
> tsp -I file HTP1.ts -P until -s 300 -P inject --poll-files --replace -p 16 NIT2.xml -O file HTP2.ts

That won't work for several reasons:
- The `file` plugin reads the TS at disk speed, so 5 minutes of TS are probably read in less that 1 second.
- The plugin `-P until -s 300` will terminate the processing and exit `tsp` after 300 seconds, _elapsed time_. For the previous reason, after 5 minutes, your file processing will have been terminated for a long time. And even if it was a real-time stream, terminating the stream is not what you want after 5 minutes.

If you want to process a file, not a real-time streaming, the TS time and the elapsed time are not correlated. You need to synchronize on the TS time.

If your TS is CBR, you can count after which packet 5 minutes have elapsed: N = (300 * bitrate) / (8 * 188).

With this command, you let PID 16 pass transparently during N packets (= 5 minutes of TS time) and then you replace it with the new NIT:
~~~
tsp -I file HTP1.ts -P filter --after-packets N --set-permanent-label 0 -P inject --only-label 0 --replace -p 16 NIT2.xml -O file HTP2.ts
~~~

Please be sure to read the description of each option in the TSDuck user's guide to understand what they do and adapt accordingly.

**Comment by Jazzykool85** [comment]
Thanks @lelegard .
In my  case the TS is CBR 42,238,562bps
and i want to make change after 3 mins instead of 5
so my N would be  = (180 * 42238562)/(8*188) = 5055147 packets

I will check with this . Thanks

**Comment by Jazzykool85** [comment]
Hi @lelegard ,

tsp -I file HTP1.ts -P filter --after-packets 5055147 --set-permanent-label 0 -P inject --only-label 0 --replace -p 16 NIT2.xml -O file HTP2.ts
The command is success,  however i am not able to get the label set for the packets hence its not working well.


F:\StreamstoIrdeto>tsp -I file HTP2.ts -P count  --only-label 0 --total --tag unit -O drop
* count: unit: total: counted 0 packets out of 0

This is the reason its not working well for inject/replace on label 0.

Do you think i need update my tool version?
F:\StreamstoIrdeto>tsp --version
tsp: TSDuck - The MPEG Transport Stream Toolkit - version 3.19-1520

**Comment by lelegard** [comment]
Sorry, I forgot option `--pid 0-0x1FFF` in plugin `filter`. 
~~~
tsp -I file HTP1.ts -P filter --pid 0-0x1FFF --after-packets N --set-permanent-label 0 -P inject --only-label 0 --replace -p 16 NIT2.xml -O file HTP2.ts
~~~

In your following command, you count packets which were tagged with label 0. But no previous filter set label 0 to any packet and it is normal to have a total count of 0.
~~~
tsp -I file HTP2.ts -P count --only-label 0 --total --tag unit -O drop
~~~
In the sample command I provided, the idea is first to set label 0 on all packets after packet N. Then, using `-P inject --only-label 0` means inject the table after packet N only. 

> Do you think i need update my tool version?

Version 3.19 is _very_ old. The current version is 3.30 and 3.31 will be released soon. So, yes, you must update.

**Comment by Jazzykool85** [comment]
Thanks @lelegard ..will check this .

**Comment by Jazzykool85** [comment]
@lelegard .Thanks a bunch, It works well.
