### ISSUE TITLE
[Q] Want to merge dvb subtitle  with video source .

### ISSUE THREAD

**Issue by prashant-09-tech** [tsduck/tsduck#1026]
could you suggest which plugin will use for it.
@lelegard

**Comment by lelegard** [comment]
To precisely mux the video, audio, subtitles components of the same service, you need a MUX. TSDuck is not a MUX. This has been discussed many times here. To do that, I would suggest to use ffmpeg.

In the same system, TSDuck and ffmeg are complementary and often used together. FFmpeg processes the content, audio, video, subtitles, muxing, and TSDuck processes the structure, signalization and data of the TS transport layer.
