### ISSUE TITLE
[BUG] Typo in tsduck User's guide

### ISSUE THREAD

**Issue by bojanra** [tsduck/tsduck#1038]
#### Bug description:
There is a mistake in the manual tsduck.docx and tsduck.pdf for **stats** plugin on page 366.

#### How to reproduce:
Usage
tsp -P pids [options]

#### Expected behavior:
Usage
tsp -P stats [options]

**Comment by lelegard** [comment]
Hi @bojanra,
Thanks for reporting this. Silly typo indeed. This is fixed.
