### ISSUE TITLE
Homebrew missing?

### ISSUE THREAD

**Issue by BartmanEH** [tsduck/tsduck#1073]
https://github.com/tsduck/homebrew-tsduck/blob/master/README.md
this page is error 404 and `brew update` yields the error: 
```
remote: Repository not found.
fatal: repository 'https://github.com/tsduck/homebrew-tsduck/' not found
Error: tsduck/homebrew-tsduck does not exist! Run `brew untap tsduck/homebrew-tsduck` to remove it.
```
Is there a problem with Homebrew support right now?

**Comment by lelegard** [comment]
Hi @BartmanEH 

TSDuck has been included in the core Homebrew repo for a while.

The one you reference was a private tap I created in the beginning of TSDuck, for TSDuck alone. It has been obsoleted for quite a while and was no longer updated. It has now been removed. Use `brew untap` as indicated. Now, `brew install tsduck` works out of the box from the regular Homebrew.

**Comment by BartmanEH** [comment]
Thank you, Thierry!
