### ISSUE TITLE
[Question] Playing a TS File with TSDuck. The continuity plugin throws there are missing packets, while in reality the TS File does not contain a single error

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#1097]
Hi @lelegard 

#### Bug description:
I'm using TSDuck to play a TS File from both a Windows Machine (v3.31-2761) and a Debian one (3.32-2978), and the `continuity` plugin throws there are missing packets, while in reality the TS File does not contain a single error:

File played from Windows with TSDuck 3.31-2761
![image](https://user-images.githubusercontent.com/81666507/198869921-c81c3004-c8c9-4df2-8755-518d813e2288.png)

File played from Debian11 (Bulleseye) with TSDuck 3.32-2978
![image](https://user-images.githubusercontent.com/81666507/198870406-b59beab9-46f4-45de-b300-2903a9819867.png)

You will notice the packet loss happen exactly at the same time, on the same PIDs, both on Windows and Debian version, with exactly the same number of packet loss for each occurrence of the logs.

I'm able to assess the TS File is 100% clean because I have analysed it with 3 different tools:
- TSDuck with tsanalyse
- Sencore CMA1820
- TSReader Pro
- PROMAX TS Analyser

All the above tools show that there is not a single TS packet with invalid sync nor transport error. You will find the screenshots attached below.

#### How to reproduce:
Download the TS file here:
https://wetransfer.com/downloads/33e87c5a4fb87eda15b4a7ab8dc5fc7020221030084417/c0f7ae1cb27bfcd9d99611570644bc7120221030084426/ccbdd8
--
1 item
Channel_NTV.ts130 MB

Use the following command:
`tsp.exe --verbose --initial-input-packets 7 --max-input-packets 7 --max-flushed-packets 7 --max-output-packets 7 -I file ..\video\Channel_NTV.ts --infinite -P regulate -P continuity --fix -O ip 224.1.1.3:10003 -l 192.168.1.118 --packet-burst 7 --enforce-burst`

I also tried a simpler command, with the same result:
`tsp.exe --verbose -I file ..\video\Channel_NTV.ts --infinite -P regulate -P continuity --fix -O ip 224.1.1.3:10003 -l 192.168.1.118 --packet-burst 7 --enforce-burst`

#### Errors and logs:
Sencore CMA1820:
![image](https://user-images.githubusercontent.com/81666507/198869824-852aa56e-0a70-4273-8aa3-7b34047a6b3d.png)

TSReader Pro:
![image](https://user-images.githubusercontent.com/81666507/198869792-820a0cec-241e-45e2-b95b-b2e639a5a53b.png)

TSDuck tsanalyze:
![image](https://user-images.githubusercontent.com/81666507/198869849-56b261e7-4ff3-4ff4-ba0a-aa52c3a1a8db.png)

PROMAX TS Analyser:
![image](https://user-images.githubusercontent.com/81666507/198877919-d361057f-1e05-4823-9e87-88a8429c5047.png)

#### Environment:
Machine1
 - OS: Windows
 - OS version: 10
 - TSDuck full version: 3.31-2761
 - Installation type: Official binary

Machine2
 - OS: Debian
 - OS version: Bullseye
 - TSDuck full version: 3.32-2978
 - Installation type: Official binary

**Comment by lelegard** [comment]
I can't analyse the file now, I am away and have nothing more than my phone. 

However, I am pretty sure that the errors appear when the file wraps up. At the end of the file, there is no reason that the continuity counters are adjacent to the one at the beginning. The `continuity` plugin analyzes a continuous stream and has no information on the nature of the input. When the file wraps up, everything is broken, CC, PCR, frames, etc. And one CC error appears once on each PID. 

Errors occur in bursts at the same place in the file, exactly one error per PID, at 700k packets, 1.4 packets, etc. So, your file must have 700k packets.

You say that your file has no CC error. If you analyse the file once, there is no error. But if you append the file to itself, the CC errors will appear at 700k packets.

**Comment by moving-digital** [comment]
Thanks a lot, Thierry. 

I think I got confused because the CC errors don't happen all at once when looping: as you can see, the PID 0x02A4 is experiencing 12 packets loss in the middle of the file, but not right after the file has looped, which is weird to me.

It would be great to get your confirmation that this is a normal behaviour.

**Comment by lelegard** [comment]
The plugin `continuity` can realize that there is a discontinuity only when it encounters the first packet of each PID after the loop back. For each PID, the discontinuity appears at index file size + index of first packet of that PID, then with a constant offset equal to the file size. 

You have to check what is this PID 0x02A4. If this is a "sparse" PID which appears at index 500k packets for the first time, the discontinuity is discovered at packet 700k (initial round) + 500k (first packet in that PID in second round) = 1.2 packets. Please check.

**Comment by moving-digital** [comment]
The PIS is the SCTE-35 DPI one.

**Comment by lelegard** [comment]
So it seems normal that nothing happens on that PID until there is an event to signal. Again, I bet that its first packet is at offset ~500k. Everything is normal. 

If you have a tool that does not report any error on the _file_, then try to double the file, ie copy it twice in a new file, with double size. Then reuse the same tool on the new file with double size and it will report the same errors as the plugin `continuity`.

**Comment by moving-digital** [comment]
Hi @lelegard 

You were right: the CC error on the SCTE-35 PID matches the time where the the cue is fired in the PID...

Sorry for the unnecessary ticket.
