### ISSUE TITLE
[Q] how to convert tsp udp to hls with multiresolution for OTT  streaming in tsduck toolkit

### ISSUE THREAD

**Issue by udhayNuk** [tsduck/tsduck#1102]
tsp -I ip 233.1.1.1:1001 -O hls --duration 3 -p master.m3u8 stream.ts

how to convert hls with multiresolution for ott streaming in tsduck

and how to delete the hls segment file after 10 segment file automatically for live streaming

tell me a full script how to delete the segment file automatically and for multiple resolution OTT streaming udp to hls

**Comment by M-Bala-2612** [comment]
Vanakkam thala
