### ISSUE TITLE
[Q] "filter" plugin negate --after-packets

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#1115]
Hi @lelegard ,

Simple question: How to obtain the effect of _negate --after-packets count_ in the `filter` plugin?

What I need to do is: filter out all packets (of a tsp processing) until one specific packet (that I know only the _number_) and after pass all others. My initial idea is to do a `-P filter --until-packets 9999 ...`, but this option is not available. And in the documentation:
```
--after-packets count
Let the specified number of packets pass transparently without filtering. Start to apply the
filtering criteria after that number of packets.
```
So it's not possible to negate it with `-P filter -n --after-packets 9999 ...`. Any idea?

**Comment by lelegard** [comment]
Why not simply `-P skip 12345`?

**Comment by lelegard** [comment]
Why not simply `-P skip 9999`?

**Comment by lars18th** [comment]
> Why not simply `-P skip 9999`?

OMG! One specific plugin for this task. So thank you. I feel this was not an stupid question.
Regards.
