### ISSUE TITLE
[BUG] Error: configuration file 'tsduck.dtv.names' not found

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#1117]
#### Bug description:

Message: `Error: configuration file 'tsduck.dtv.names' not found`
And the file is not inside the package.

#### How to reproduce:

Execute any tsp.exe processing.

#### Environment:
 - OS:  Windows
 - OS version: 10
 - TSDuck full version:  `TSDuck-Win64-3.32-2983-Portable.zip`
 - Installation type: PORTABLE

**Comment by lelegard** [comment]
This is correct. I just fixed it. The two `.zip` files were just updated with the fix and the script to build the installers on Windows has been fixed. You can download the package again.

The XML model for tables was missing too. These two files were huge monolithic source files. Becoming too large, they were modularised in the source tree and the final files are now generated during the build. The build was updated in the Makefiles for Linux, macOS, FreeBSD and the NSIS Windows installer script was updated too. The so-called portable zip packages were forgotten.

**Comment by lars18th** [comment]
Thank you!
