### ISSUE TITLE
[Q] Dektek card PCIe DTA-2172

### ISSUE THREAD

**Issue by Litrona** [tsduck/tsduck#1126]
Hi Lelegard, 
Do you know if Dektek card PCIe model DTA-2172, can be used as ASI input and output from the tsp cmdline ?.
Thanks in advance.
Regards

**Comment by lelegard** [comment]
Hi @Litrona 

I do not have such card to test. However, the Dektec API is very reliable across devices. So, you have to try but I would bet it works correctly. Use the command `tsdektec` to list the ports and set a given port in input or output mode. Once a port is set in either input or output mode, it is recognized by either the input or output `dektec` plugin.
