### ISSUE TITLE
[FEAT] HLS output "--custom-tag"

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#1129]
Hi @lelegard ,

I hope you don't be warned because I open "another" issue for enhancements in the HLS output. In this case is another simple enhancement related with the previous, but I feel you prefer to leave different topics separate.

Idea: Add the option `--custom-tag <STRING>` to add in the playlist a user specific tag.

Example: `#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=...` To add addtional descriptions of the stream.

My objective is to insert this tag: `#EXT-X-MEDIA:TYPE=MP2T` that is _NOT STANDARD_ to describe optionally the stream when using the `--slice-only` option of #1127. Then it will be more easy to identify these "special" HLS streams. But in any case, this will not be part of the TSDuck toolkit, as it will be used from the command line. So the toolkit will continue to be clean. And the proposed solution will be useful for other users to incorporate other standard tags.

I hope you want to accept this.
Regards.

**Comment by lelegard** [comment]
Done
