### ISSUE TITLE
Real time IP analysis

### ISSUE THREAD

**Issue by przemo1983** [tsduck/tsduck#1144]
I am using following command to analyze IP UDP stream: 
`tsp -I ip 239.39.39.39:3939 -l 10.8.8.1 --receive-timeout 10000 -P analyze -o ip.analysis.normalized --normalized -i 2 -O drop`
Each time when new analysis is performed the analysis context is reset.

Is it possible to add a parameter that the analysis context will not be reset each time (after -i X)? 
This will be very helpful to make real time UDP stream analysis over some longer time period but with cyclic updates of errors/data. Of course the file(s) should be updated each -i X value (with correct values from beginning of analysis) to get those values for further analysis.

**Comment by lelegard** [comment]
Good idea. Will do...

**Comment by lelegard** [comment]
Option `--cumulative` has been added.
