### ISSUE TITLE
[Q] How to remove all null packets from TS

### ISSUE THREAD

**Issue by Ulfila80** [tsduck/tsduck#1161]
Is it possible to remove all null packets from input TS? Input TS is CBR, but usefull payload may be CBR or VBR. Tried 'reduce' plugin, but have no luck.

**Comment by lelegard** [comment]
Use `tsp .. -P filter -n -p 0x1FFF ...`
Please RTFM for more details.

**Comment by Ulfila80** [comment]
Thank you very much! That is what I need! Forgot that null packets have pid 0x1FFF.
