### ISSUE TITLE
[Q] How can I inject the NIT table and the AIT table into a TS that does not contain these tables?

### ISSUE THREAD

**Issue by alvarollgo** [tsduck/tsduck#1184]
Hi,

I want to add these two tables (NIT and AIT) in a transport stream that does not contain these tables.  And I have two xml files with default tables. I have been trying with the plugins `-P nit` and `-P inject` but I have not succeeded.

Can you help me? Thanks in advance and best regards.

**Comment by lelegard** [comment]
The most common reason for tables not being injected is the absence of "free space" (aka stuffing, aka null packets) in the TS. Please read the reference doc for tsp in the user's guide, especially the section "modifying, inserting and deleting packets".

**Comment by alvarollgo** [comment]
Oh yes, that was my problem, the absence of null packets in the ts. Thanks!

I was able to inject the NIT table without any problems with `-P inject`. Now, what bitrate and repetition interval values are suitable for the AIT table?

Best regards

**Comment by lelegard** [comment]
> Now, what bitrate and repetition interval values are suitable for the AIT table?

Did you read the various DVB implementation guidelines?

**Comment by alvarollgo** [comment]
Resolved! Thank you very much!
