### ISSUE TITLE
Want to convert HLS to UDP

### ISSUE THREAD

**Issue by prashant-09-tech** [tsduck/tsduck#1202]
Hi , I am converting hls to Udp and facing some problem in output video .
I am using this command
tsp -I hls --highest-bitrate "https://d24i14cm25hove.cloudfront.net/v1/master/b2ddbd226489c66469bd84b14f17b98243bd0e01/FAST-PMSL-NAB/index.m3u8" -P pcrbitrate -P regulate   -O ip 127.0.0.1:10203

And the output video have some jerk .

@lelegard  please suggest which command is useful for this .

**Comment by lelegard** [comment]
Hi @prashant-09-tech 

Is your stream CBR or close to CBR? HLS streams are usually VBR to "very VBR".

The plugin `regulate` regulates the flow on the basis of an average bitrate. When the bitrate is "very variable" on short intervals, it won't work correctly. 

You may try `-P regulate --pcr-synchronous` to see if it improves the stability. In that case, the average bitrate is ignored and the regulation is based on PCR's in the stream.
