### ISSUE TITLE
while converting hls to hls when input get stopped for few seconds it shows Error: hls: no URL specified error, after input recived it does not reconnect to it[BUG] 

### ISSUE THREAD

**Issue by prabhavathis08** [tsduck/tsduck#1213]
#### Errors and logs:

~~~
[be sure to surround verbatim log lines with "~~~" lines]
~~~

#### Environment:
 - OS: 
 - OS version: 
 - TSDuck full version: 
 - Installation type:

**Comment by lelegard** [comment]
Please describe a precise analysis of your problem, including all required information in the template. A long title has never been a valid bug analysis.
