### ISSUE TITLE
[Q] How do I inject new SCTE-35 markers in a TS file which had splice data originally?

### ISSUE THREAD

**Issue by Wolfy76700** [tsduck/tsduck#1216]
*Using TSDuck 3.34-3197 on Ubuntu 20.04 LTS*

Hi, I am currently looking into the possibility of repackaging a TS file into a new TS file which has SCTE-35 splice data. To do that, I've extracted splice data from my TS file as a JSON thanks to the `splicemonitor` using the command below:

`tsp -I file source.ts -P splicemonitor -o scte35.json --json -O drop`

I then tried to reinject the splice data from the `scte35.json` file into said TS using this command:

`tsp -I file source.ts -P spliceinject --files scte35.json --pid 321 --pts-pid 256 --max-file-size 10000 -O file > new.ts`

However I have this error popping up:

`* Error: spliceinject: unexpected node <event> in <tsduck>, line 0`

I also tried doing the insertion on a version of the TS which had its splice data and its metadata removed thanks to `ffmpeg`, but to no avail. Am I missing something when it comes to reinserting the splice data?

**Comment by lelegard** [comment]
Hi @Wolfy76700 

The output of `splicemonitor` is a monitoring report, not tables. With `--json`, the monitoring report is parseable by tools but it still does not contain tables.

If you want to extract the splice information tables and reinject them later, use `tstables` (or the equivalent `tsp ... -P tables`).

If you do not care about modifying the extracted tables, prefer the XML format over JSON. In practice, tables are extracted and injected in XML format. Using JSON simply adds an additional layer of automated XML<=>JSON translation which is useless if you simply want to extract and reinject.

**Comment by Wolfy76700** [comment]
Hi @lelegard 

See, the reason why I was experimenting with the JSON output is because ultimately I want to insert different SCTE-35 data into the stream. The idea of reinjecting the same SCTE-35 data was merely to acquaint myself with how to use the plugin.

Neverhteless, I have also tried extracting the data using the `tstables` XML output and then reinjecting it into the cleaned feed, to no avail. These were the commands I used:

```
tsp -I file source.ts -P tables --text plp0.splice-info-tables.txt --xml plp0.splice-info-tables.xml -O drop
tsp -I file source_clean.ts -P spliceinject --files plp0.splice-info-tables.xml --pid 321 --pts-pid 256 --max-file-size 10000 -O file > new.ts
```

**Comment by lelegard** [comment]
Your `tsp -P tables` command extracts all tables in the TS: PAT, PMT, SDT, etc. Splice information tables are mixed in the middle of these. Specify the PID where the splice information tables are in order to limit the extraction of tables. Or specify the splice table id. RTFM for more details on the `tables` plugin.

**Comment by Wolfy76700** [comment]
Filtering on PID 321 where the splices are in the original file doesn't change anything, I'm still not getting any splices in the new file. Additionally, I have also tried regenerating the clean feed using tsduck, to no avail. Here are the commands run:

```tsp -I file source.ts \
    -P tables \
              --text plp0.splice-info-tables.txt \
              --xml plp0.splice-info-tables.xml \
              --json plp0.splice-info-tables.json \
              --pid 321 \
    -O drop

tsp -I file source.ts \
    -P filter -n -p 321 \
    -O file > source.ts

tsp -I file source.ts \
    -P tables \
              --text plp0.splice-info-tables-clean.txt \
              --xml plp0.splice-info-tables-clean.xml \
              --json plp0.splice-info-tables-clean.json \
    -O drop

tsp -I file source_nosplice.ts \
    -P spliceinject --files plp0.splice-info-tables.xml --pid 321 --pts-pid 256 --max-file-size 10000 \
    -O file > new.ts

tsp -I file new.ts \
    -P tables \
              --text plp0.splice-info-tables-new.txt \
              --xml plp0.splice-info-tables-new.xml \
              --json plp0.splice-info-tables-new.json \
              --pid 321 \
    -O drop
```

**Comment by lelegard** [comment]
Things to check:
- Make sure that the PTS in the new file are the same as in the previous file. Splice injection is synchronized on PTS.
- Make sure that the new TS has sufficient "free space" (ie. stuffing) to insert new packets. This is the most common cause for failure to insert anything, splice information or other. See other topics in this forum.

**Comment by Wolfy76700** [comment]
I should have the same PTS given that my new file, the one generated by the script in my previous comment, is just a copy of the original file without the 321 SCTE-35 track, shouldn't I? Am I missing something obvious?

**Comment by lelegard** [comment]
So this is a clear symptom that your problem is an absence of free space in the TS.

Using `--add-start-stuffing` adds stuffing at the beginning of the TS. This is not what you want. Use `--add-input-stuffing` for regular stuffing addition. Do not forget to remove the remaining useless stuffing at the end of the pipe.

Please [RTFM](https://tsduck.io/download/docs/tsduck.pdf), see the tsp reference documentation in chapter 3, especially the section named “modifying, inserting and deleting packets”.

**Comment by Wolfy76700** [comment]
OK adding stuffing seems to fix the problem, though I'm still getting the descriptors doubled. Thank you very much!
