### ISSUE TITLE
Some help with run a plugin? plugin no found cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by pico2000** [tsduck/tsduck#1217]
Hi , someone can help ? I installed TSDUCK version 3.34 ubuntu 20.4 . When I tried to run this command I have this error:

tsp -I ip 239.1.1.42:6042 -P tsfixcc --fix -O ip 224.2.2.2:1234 

* Error: tsfixcc.so: cannot open shared object file: No such file or directory
* Error: processor plugin tsfixcc not found

thanks,

**Comment by lelegard** [comment]
Please RTFM.

`tsfixcc` is a standalone executable, just like `tsp`. This is not a plugin.

The related plugin is named `continuity`.

**Comment by pico2000** [comment]
ok let me check the TFM.
