### ISSUE TITLE
Is it possible to set a audio bitrate ? [Q] 

### ISSUE THREAD

**Issue by Swetha081099** [tsduck/tsduck#1218]

**Comment by lelegard** [comment]
Hi @Swetha081099 

What do you mean by "set an audio bitrate"?

If you mean "reencode an audio elementary stream at a higher/lower bitrate", then you should use tools such as ffmpeg or any other audio/video editor. TSDuck works on the transport layer, it does not mux, decode or encode the audio/video content.
