### ISSUE TITLE
[FEAT] Add to the tsanalyze app, EIT values contained in the SDT table

### ISSUE THREAD

**Issue by Litrona** [tsduck/tsduck#1225]
I usually use tsanalyze --json <file.ts> to obtain all the useful PSI info I need. 
However in the Services node, I miss some important values such as "EIT_schedule" and "EIT_present_following". 
I guess you are already parsing the SDT table, cos I can see the service name and provider in the list of variables exposed.
Could you please add it, in a future enhancement ? 
Thanks and best regards

**Comment by lelegard** [comment]
Hi @Litrona 

The output of `tsanalyze` is a synthetic overview of the TS. There are lots of important information from the PMT's, SDT or NIT. Each user has his preferences about which one is important. If we include all, the output will be bloated, no longer synthetic, and other users will complain.

The JSON output contains exactly the same information, not more, just in JSON format.

To extract the precise information you need, you have to extract the corresponding tables. All details are here.

If you prefer JSON for everything, and collect everything in one pass, use:
~~~
tsp -I file file.ts \
    -P analyze --json --output-file ts.json \
    -P tables --pid 17 --tid 66 --json-output sdt.json \
    -O drop
~~~

The synthetic information is in `ts.json`. All information from SDT are in `sdt.json`. You can also extract any other table of interest.
