### ISSUE TITLE
[BUG] PESDemux: PES Packets Made Of A Single TS Packet Are Delayed Until Next PUSI

### ISSUE THREAD

**Issue by mich181189** [tsduck/tsduck#1232]
#### Bug description:
When a TS Packet contains an entire PES packet, the handler is not invoked until the next packet starts, as would be the case for undefined length packets. This is not a problem if the stream is regular, but in case of irregularly spaced data, such as subtitles, this can cause a considerable delay in processing (multiple minutes in the example I came across!)

#### How to reproduce:
Feed a PESDemux a PES packet contained within a single TS packet. Note the handler is not invoked until the next payload starts.

#### Expected behavior:
The handler should be immediately invokes

#### Environment:
 - OS: Linux
 - OS version: Fedora 36
 - TSDuck full version: 3.35-3227
 - Installation type: Official or git - bug is present in both

#### Additional information:
The problem is the "do we have enough data" check is only carried out from the second packet onwards. 
A fix for this would be something like the pull request that references this issue. This basically copies the length check from the continuation path into the initial packet path. This feels a little messy, but is perhaps the best way to handle things

**Comment by lelegard** [comment]
PR #1233 merged
Thanks @mich181189
