### ISSUE TITLE
[BUG] SRT option `--linger` is not working

### ISSUE THREAD

**Issue by sylvain-apivideo** [tsduck/tsduck#1234]
#### Bug description:
The ``--linger`` SRT option is currently not working, and generate an error when used.

#### How to reproduce:
Run the command: `tsp -I srt --listener 127.0.0.1:6000 --linger 10 -O drop`

#### Expected behavior:
The command is successful, and socket is configured with the configured linger timeout

#### Errors and logs:
~~~
* Error: srt: error during srt_setsockflag(SRTO_LINGER): Operation not supported: Bad parameters
~~~
#### Environment:
 - OS: Linux
 - OS version: Ubuntu 22.04
 - TSDuck full version: 3.33-3139
 - Installation type: official binary

#### Additional information:
It appears the socket option is configured with an integer where it would expect a `struct linger`

**Comment by lelegard** [comment]
Hi @sylvain-apivideo 

Thanks for reporting this. Silly mistake indeed. I fixed it.

You can rebuild from the current state of the repo or wait for the next nightly build. Will be version 3.35-3231.

**Comment by sylvain-apivideo** [comment]
That was fast.
Thanks for fixing it.
