### ISSUE TITLE
[Q] Cannot get TSDuck to demux, get tables

### ISSUE THREAD

**Issue by ankitp86** [tsduck/tsduck#1258]
So I have a live TS stream running, and my application is able to capture raw TS packets at some interval. What I'm trying to do is feed these TS packets to TSDuck so that it can demux these packets. At some later time I want to be able to see what Tables and PIDs where "detected" from the captured samples.

This seems very similar to what tsTSScanner code is doing; however I do not seem to get call backs on `handleTable`
I believe it is registered demux class.

Here is the simplified code:
```
#include "tsduck.h"

#include "mydata.h"
/* snippit of mydata.h
  ...
  const uint32_t mydata_size = 32000;
  uint8_t mydata_raw[mydata_size][188] = {
    {0x47, 0x00, 0x6C, 0xFC, 0xD2, 0x3E, 0x22, ... },
    {0x47, 0x00, 0x00, 0x8F, 0xBF, 0xDB, 0xCF, ... },
    ...
  };
*/

class MyClass : private ts::TableHandlerInterface {
  public:
    MyClass();

    void parse(uint8_t* buf);
  
  private:
    ts::DuckContext   _duck;
    ts::SectionDemux  _dmux;
    ts::TSPacket      _packet;

   virtual void handleTable(ts::SectionDemux&, const ts::BinaryTable&) override;
};

MyClass::MyClass() :
    _duck(),
    _dmux(_duck, this)
{
  // Collect PAT, SDT, NIT
  _dmux.addPID(ts::PID_PAT);
  _dmux.addPID(ts::PID_SDT);
  _dmux.addPID(ts::PID_NIT);
}

void MyClass::handleTable(ts::SectionDemux&, const ts::BinaryTable& table) {
  std::cout << "MyClass handleTable Called" << std::endl;
}

void MyClass::parse(uint8_t* buf) {

  std::stringstream sstream;
  sstream.write((const char*)buf, 188);
    
  if (_packet.read(sstream, true)) {
    _dmux.feedPacket(_packet);
  }
}

int main() {
  
  std::cout << "ENTER" << std::endl;

  MyClass p;

  for (int i = 0; i < mydata_size; ++i) {
    p.parse(mydata_raw[i]);
  }

  std::cout << "EXIT" << std::endl;
  return 0;
}
```

When I print the info on `_packet` I see they are valid. When I print the status of `_dmux` I get:
```
Invalid TS packets: 0
TS packets discontinuities: 0
Scrambled TS packets: 4,570
Invalid section lengths: 0
Truncated sections: 0
Invalid section index: 0
Invalid unchanged section version: 0
Corrupted sections (bad CRC): 0
Next sections (not yet applicable): 0
```

This leads me to believe they are getting into the demux... but not sure why `handleTable` is not called. I should have enough packets to have a complete table filled... any help, ideas would be good..

**Comment by lelegard** [comment]
Hi @ankitp86 

Did you try to store your binary data in a file and run `tstables` on it?
This is typically the same as what you do.
Does it display some tables?

BTW, no need to make simple things complicated:
~~~
void MyClass::parse(uint8_t* buf) {
  _dmux.feedPacket(*reinterpret_cast<ts::TSPacket*>(buf));
}
~~~
