### ISSUE TITLE
How to Rename the Output Bin Files

### ISSUE THREAD

**Issue by M-Bala-2612** [tsduck/tsduck#1262]
```
   https://github.com/tsduck/tsduck/archive/refs/tags/v3.34-3197.tar.gz
   cd tsduck-3.32-2983
   scripts/install-prerequisites.sh
   make installer
   sudo dpkg -i installers/tsduck_3.34-3197.ubuntu20_amd64.deb
```
   
Hello... @lelegard 
I was Compile the TSDuck Using this Commands , 
How to Change the Output Bin Files name. which directory file was output bin name allocated files in the Source code
Like tsp name change to StreamingBin

Thankyou!!!

**Comment by lelegard** [comment]
A TSDuck installation contains many files, binaries and configuration files, in a well-defined organization. 

You can change the installation root during `make install` but the file names and organizations remain the same. 

You use `make installer` which creates a standard package, rpm or deb, which is even more "standard". 

If you want to customize the file names of the binaries, feel free to try but there is no supported way and there won't be any in the future. 

TSDuck is open source and you are free to modify anything (within the liberal limits of the BSD-2 license). But this becomes your project and if you break something, you won't have support to fix it.

**Comment by M-Bala-2612** [comment]
Okey @lelegard .
I was Changed some bin files name manually, 
But Changed bin file was not worked , any other way to Change the Bin file name in the Source Code

**Comment by M-Bala-2612** [comment]
Okey @lelegard .

I was Changed some bin files name manually,
But Changed bin file was not worked , any other way to Change the Bin file name in the Source Code.

which directory file was Output Bin name allocated 

Thankyou !!!

**Comment by udhayNuk** [comment]
@M-Bala-2612 
its your wish dont ask any more fucking questions.

**Comment by M-Bala-2612** [comment]
Okey @lelegard .

I was Changed some bin files name manually,
But Changed bin file was not worked , any other way to Change the Bin file name in the Source Code.

which directory file was Output Bin name allocated

Thankyou !!!

**Comment by M-Bala-2612** [comment]
@lelegard 
Its Possible to Combine the all Bin file to Single Bin file ?

Thankyou !
