### ISSUE TITLE
HOW TO STORE THE UDP CONTENT WHEN STREAMING ONE UDP TO ANOTHER UDP? 

### ISSUE THREAD

**Issue by udhayNuk** [tsduck/tsduck#1263]
@lelegard 

tsp -v -m --synchronous-log -I ip 224.2.2.1:5000 -P regulate --pcr-synchronous -O ip -l 127.0.0.1 235.1.1.1:1234 

this is my udp to udp conversion.

i want to store the output udp content in STORE.TS in ts file or any other idea please give me.

if its possible means tell me the how to store when streaming udp to udp content.

thank you in advance.

**Comment by M-Bala-2612** [comment]
Are you crazy @udhayNuk 
Read the User guide .

**Comment by AlfonZ42** [comment]
Hello.

Does *file* plugin not work in your case, i.e. `... -P file STORE.TS ...`?

**Comment by udhayNuk** [comment]
@AlfonZ42 
i have already this method.
but i want any another method.

**Comment by AlfonZ42** [comment]
I'm not sure what you mean.

Are you saying that you have tried the *file* plugin, it worked, but you want to do one thing via two different methods? 

Or are you saying you have already tried the *file* plugin but it doesn't work for what you wan to achieve? In which case could you please describe what is not working for your case?

**Comment by udhayNuk** [comment]
@AlfonZ42 
i have tried it has been working i want another method.

**Comment by lelegard** [comment]
The `file` plugin, as recommended by @AlfonZ42, is _the_ method. 

That being said, TSDuck is open source and you may invent and implement any other method for your own usage.

**Comment by M-Bala-2612** [comment]
Fuck your Question @udhayNuk  ...
Read the User guide
