### ISSUE TITLE
Is too hard to find so many request[Q] 

### ISSUE THREAD

**Issue by zouji2012** [tsduck/tsduck#1268]
[root@localhost soft]# rpm -Uvh tsduck-devel-3.34-3197.el9.x86_64.rpm
error: Failed dependencies:
        libcurl-devel is needed by tsduck-devel-3.34-3197.el9.x86_64
        libedit-devel is needed by tsduck-devel-3.34-3197.el9.x86_64
        pcsc-lite-devel is needed by tsduck-devel-3.34-3197.el9.x86_64
        pkgconfig(libcurl) is needed by tsduck-devel-3.34-3197.el9.x86_64
        pkgconfig(libedit) is needed by tsduck-devel-3.34-3197.el9.x86_64
        pkgconfig(libpcsclite) is needed by tsduck-devel-3.34-3197.el9.x86_64
        pkgconfig(libusb-1.0) is needed by tsduck-devel-3.34-3197.el9.x86_64
        pkgconfig(srt) is needed by tsduck-devel-3.34-3197.el9.x86_64
        rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by tsduck-devel-3.34-3197.el9.x86_64
        srt-devel is needed by tsduck-devel-3.34-3197.el9.x86_64
        tsduck = 3.34-3197.el9 is needed by tsduck-devel-3.34-3197.el9.x86_64

When i m install tsduck  So many request need 。。
anyone canhelp package them 。
try my best can not find all.

**Comment by lelegard** [comment]
Hi @zouji2012 

First, you must have noticed that the package file name contains `.el9`. So, the fist question is: do you use Red Hat Enterprise Linux 9 or one of its clones ? 

If the answer is no, then this package cannot be installed. 

If the answer is yes, then simply `dnf install` all requested packages. Except the `tsduck` package of course which must be manually installed.

**Comment by zouji2012** [comment]
> Hi @zouji2012
> 
> First, you must have noticed that the package file name contains `.el9`. So, the fist question is: do you use Red Hat Enterprise Linux 9 or one of its clones ?
> 
> If the answer is no, then this package cannot be installed.
> 
> If the answer is yes, then simply `dnf install` all requested packages. Except the `tsduck` package of course which must be manually installed.

Thank you very much for your reply 。。

![image](https://github.com/tsduck/tsduck/assets/62059465/9f277237-7f5a-44e8-8777-7d6159eca819)
I tried Centos 9 ,some of the request installed ,  still  can not  use DNF to install these .
i also tey to search in the internet  ,, even after i install  pcsc-lite-devel-1.9.1-4.el9.aarch64.rpm
![image](https://github.com/tsduck/tsduck/assets/62059465/24205556-0c89-4352-be27-9597c35a6b5e)
got more issue ,   
i am noob
do you have some suggention to me ?
thank you!

**Comment by lelegard** [comment]
Run this:
```
dnf install libcurl-devel libedit-devel pcsc-lite-devel srt-devel
```

And then use rpm to install TSDuck and tsduck-devel

**Comment by zouji2012** [comment]
![image](https://github.com/tsduck/tsduck/assets/62059465/294bdfe4-cd1f-4002-9cf8-3aa8a83bd010)
maybe i need check my repo ？

**Comment by zouji2012** [comment]
[root@localhost soft]# rpm -Uvh tsduck-devel-3.34-3197.el9.x86_64.rpm
error: Failed dependencies:
        tsduck = 3.34-3197.el9 is needed by tsduck-devel-3.34-3197.el9.x86_64
  finally i found all the request ，but new alarm 。。
![image](https://github.com/tsduck/tsduck/assets/62059465/1f406d93-649c-4e17-ae01-e88e796cc3ae)

**Comment by zouji2012** [comment]
> Run this:
> 
> ```
> dnf install libcurl-devel libedit-devel pcsc-lite-devel srt-devel
> ```
> 
> And then use rpm to install TSDuck and tsduck-devel

thank you again i have finished install all the  request !!
