### ISSUE TITLE
How to Use TsAnalyzer [Q] 

### ISSUE THREAD

**Issue by zouji2012** [tsduck/tsduck#1278]
Hi ：
![image](https://github.com/tsduck/tsduck/assets/62059465/c9e6020b-8d10-4bc6-86df-66e95c71417e)
I learning to use TSAnalyzer，  
 The input file of TSAnalyzer only can be a file? Can I directly analyze UDP multicast streams as input? Also, the method I am currently using is to record a bit stream using ffmpeg and then have TSAnalyzer analyze it. Do you recommend a simpler solution?

thanks！

**Comment by lelegard** [comment]
Hi @zouji2012 

Use the `analyze` plugin in a `tsp` command. Use `-O drop` to discard the output stream. Read the user's guide for more details and examples.
