### ISSUE TITLE
[Q] Can you scramble a PID without fixed CW 

### ISSUE THREAD

**Issue by xfiles2007** [tsduck/tsduck#1280]
Is it possible to scramble a PID without a fixed CW input file.

I have transport stream and I wish to encrypt a specific PID (Video file only, not audio for example) but want to connect it to my ecmg. Encrypting the whole service with ecmg is no issue but I just want 1 specific PID.

When I specify the the PID I get this error : 

* Error: scrambler: specify control words to scramble an explicit list of PID's

**Comment by xfiles2007** [comment]
Encrypting the whole service with ecmg is no issue but I just want 1 specific PID.

**Comment by lelegard** [comment]
Typically, an ECMG is used to scramble a service, meaning the video PID and, most of the time, all audio PID's. The options `--no-audio` and `--no-video` can leave audio or video PID's in the clear. Do you have a different use case?
