### ISSUE TITLE
Wants to Convert Mpts to Spts in Ts file

### ISSUE THREAD

**Issue by prashant-09-tech** [tsduck/tsduck#1281]
Hi, @lelegard 
I am using this command to convert Mpts to Spts in ts file .
tsp -I ip 10201 -P pcrbitrate  -P fork  "tsp -P filter --pid 101 -O ip 
127.0.0.1:10207" -P fork "tsp -P filter --pid 301 -O ip 127.0.0.1:10208" 
-P fork "tsp -P filter --pid 401 -O ip 127.0.0.1:10209" -P filter --pid 
201 -O ip 127.0.0.1:10206

but I am not getting the proper result .

**Comment by lelegard** [comment]
> I am using this command to convert Mpts to Spts in ts file .

The command you posted does not do this. It sends a few individual PID's in distinct UDP output. And this is certainly not a file.

The proper plugin to extract a service (MPTS to SPTS) is `zap`. Please RTFM for more details.

**Comment by prashant-09-tech** [comment]
Thank you for the  suggestion .
