### ISSUE TITLE
support MPTS mux

### ISSUE THREAD

**Issue by samerajarmeh** [tsduck/tsduck#130]
Thanks for best MPEG-TS tool i worked with..
its more powerfull if supports multible spts services and mux them in mpts with cbr bitrate and send them over asi or dvb modulator..
output may be a .XML table file like extracted from tstabcomp .
input may be multible udp inputs or multible dvb adapters.
its will be full mpeg dvb tool ..

**Comment by joolzg** [comment]
upipe/open broadcaster are supposed to have a really good mux, but ive tried to get it working and all the help i got was "look in open broadcaster to see how it works"

https://github.com/kierank/libmpegts
