### ISSUE TITLE
[BUG] Donation Link is Broken

### ISSUE THREAD

**Issue by fennewald** [tsduck/tsduck#1307]
I've begun using tsduck in a professional context, and would like to convince my employer to support the work done developing it. However, the link in https://tsduck.io/donate/ takes users to a paypal page that reads "This organization is currently ineligible to receive donations."

**Comment by lelegard** [comment]
Under investigation with PayPal. Thanks for notifying this.

**Comment by lelegard** [comment]
Finally, after six months of struggle, Paypal has finally unlocked the account. Donations are now possible again.
