### ISSUE TITLE
[Q]  TS-over-IP: options for --smpte-2022-fec, what do they mean?

### ISSUE THREAD

**Issue by sstaty** [tsduck/tsduck#1322]
On page 218 of TSDuck manual, for TS-over-IP for dektec devices, there is --smpte-2022-fec options (image attached). From the name of the options, it is not clear what the differences are. From smpte-2022 standard, there should be in options: no FEC, 1D FEC, 2D FEC. 

![image](https://github.com/tsduck/tsduck/assets/37019349/eac11cd5-0b66-4c06-9f7f-a112220608d5)

**Comment by lelegard** [comment]
Hi @sstaty 

These command line options are directly passed to the Dektec DTAPI. See the Dektec documentation "DTAPI Reference - Core Classes.pdf", page 118:

<img width="692" alt="image" src="https://github.com/tsduck/tsduck/assets/5641922/09eb384f-1eb8-44a7-b862-d7a311ed344c">

Generally speaking, the `dektec` plugins are simple (?) command line wrappers on top of DTAPI to read or write a transport stream. Any information on the interpretation of such or such option shall be retrieved from the Dektec documentation. This is a Dektec question, not a TSDuck question.

**Comment by sstaty** [comment]
Yes, you are absolutely right - sorry I did not realize this is directly from DTAPI. Thank you for clarification.
