### ISSUE TITLE
[Q] how to extract mpeg-ts

### ISSUE THREAD

**Issue by atplsx** [tsduck/tsduck#1329]
please help me
~~~
tsanalyze.exe 0000000100000002STR

===============================================================================
|  TRANSPORT STREAM ANALYSIS REPORT                                           |
|=============================================================================|
|  Transport Stream Id: ............. Unknown  |  Services: .............. 0  |
|  Bytes: ....................... 291,848,192  |  PID's: Total: .......... 5  |
|  TS packets: .................... 1,552,384  |         Clear: .......... 0  |
|     With invalid sync: .................. 0  |         Scrambled: ...... 5  |
|     With transport error: ............... 0  |         With PCR's: ..... 1  |
|     Suspect and ignored: ................ 0  |         Unreferenced: ... 4  |
|-----------------------------------------------------------------------------|
|  Transport stream bitrate, based on ....... 188 bytes/pkt    204 bytes/pkt  |
|  User-specified: ................................... None             None  |
|  Estimated based on PCR's: ............... 26,078,944 b/s   28,298,429 b/s  |
|  Selected reference bitrate: ............. 26,078,944 b/s   28,298,429 b/s  |
|-----------------------------------------------------------------------------|
|  Broadcast time: ................................... 89 sec (1 min 29 sec)  |
|-----------------------------------------------------------------------------|
|  Srv Id  Service Name                              Access          Bitrate  |
|                                                                             |
|  Note 1: C=Clear, S=Scrambled                                               |
|  Note 2: Unless specified otherwise, bitrates are based on 188 bytes/pkt    |
===============================================================================


===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 1,194, PID's: 1 (clear: 0, scrambled: 1)                       |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. S       20,058 b/s  |
|   Subt.  Global PSI/SI PID's (0x00-0x1F) .............. S       20,058 b/s  |
|  0x0000  PAT .......................................... S       20,058 b/s  |
|=============================================================================|
|  Unreferenced PID's                                                         |
|  TS packets: 1,551,190, PID's: 4 (clear: 0, scrambled: 4)                   |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Unreferenced PID's ........................... S   26,058,886 b/s  |
|  0x1293  Unreferenced ................................. S       20,058 b/s  |
|  0x12F7  Unreferenced ................................. S   25,694,106 b/s  |
|  0x135B  Unreferenced ................................. S      266,235 b/s  |
|  0x13BF  Unreferenced ................................. S       78,486 b/s  |
===============================================================================


===============================================================================
|  PIDS ANALYSIS REPORT                                                       |
|=============================================================================|
|  PID: 0x0000 (0)                                                       PAT  |
|-----------------------------------------------------------------------------|
|  Global PID                Transport:                Discontinuities:       |
|  Bitrate: .... 20,058 b/s  Packets: ......... 1,194  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ..... 1,194                            Unit start: ... 1,194  |
|=============================================================================|
|  PID: 0x1293 (4755)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: .... 20,058 b/s  Packets: ......... 1,194  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ..... 1,194                            Unit start: ... 1,194  |
|=============================================================================|
|  PID: 0x12F7 (4855)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate:  25,694,106 b/s  Packets: ..... 1,529,476  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ........ 8,137  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: . 1,529,476  TSrate: . 26,078,944 b/s  Unit start: ... 4,480  |
|                                                                             |
|  Clock values range:                                                        |
|  PCR: ............. 3,688                                                   |
|  from . 1,294,448,517,686                                                   |
|  to ... 1,296,864,661,050                                                   |
|  Leaps: ............... 0                                                   |
|=============================================================================|
|  PID: 0x135B (4955)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ... 266,235 b/s  Packets: ........ 15,848  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: .......... 310  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: .... 15,848                            Unit start: ..... 310  |
|=============================================================================|
|  PID: 0x13BF (5055)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: .... 78,486 b/s  Packets: ......... 4,672  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: .......... 465  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ..... 4,672                            Unit start: ..... 467  |
===============================================================================


===============================================================================
|  TABLES & SECTIONS ANALYSIS REPORT                                          |
===============================================================================
~~~

i use this commands

~~~
tsp -I file 0000000100000002STR -P descrambler -c e7b8e75466530c3cf7238f577e18618a  -O file output.ts
* Error: descrambler: invalid control word "e7b8e75466530c3cf7238f577e18618a", specify 16 hexa digits
* Error: descrambler: specify either a service or a list of PID's

tsp -I file 0000000100000002STR -P descrambler -c e7b8e75466530c3cf7238f577e18618a  -p 4855 -O file output.ts
* Error: descrambler: invalid control word "e7b8e75466530c3cf7238f577e18618a", specify 16 hexa digits
* Error: descrambler: specify control words to descramble an explicit list of PID's
~~~

i have aes-key
~~~
0x2fe17e8:      0xe7    0xb8    0xe7    0x54    0x66    0x53    0x0c    0x3c
0x2fe17f0:      0xf7    0x23    0x8f    0x57    0x7e    0x18    0x61    0x8a
~~~

**Comment by lelegard** [comment]
By default, the descrambler plugins uses the DVB-CSA2 encryption algorithm, which takes a 64-bit key (16 hex digits).

It seems that you provide a 128-bit key, probably an AES key.

The first thing you need to know is the kind of encryption you want to descramble. AES-128, ok, but which one at TS packet level? The descrambler plugin supports AES-CBC, AES-CTR, ATIS-IDSA, DVB-CISSA. All of them are AES-128 but with different modes. There is an option for each of them in the descrambler plugin. With AES-CBC and AES-CTR, be sure to know the initialization vector first (option `--iv`). RTFM for the details.

**Comment by atplsx** [comment]
I don't know the -iv value, how can I find it, which of these values ​​could it be? Can you help me?
If I need to specify the pid, which one should I specify?
0x2fe17e8:      0xe7    0xb8    0xe7    0x54    0x66    0x53    0x0c    0x3c
0x2fe17f0:      0xf7    0x23    0x8f    0x57    0x7e    0x18    0x61    0x8a
I actually do this with this program https://github.com/openlgtv/epk2extract, but since the records are divided into pieces, there are corruptions when combining them with ffmpeg concat. That's why I wanted to try this. In this program, the only value is e7b8e75466530c3cf7238f577e18618a I enter this.

**Comment by atplsx** [comment]
tsp -I file 0000000100000002STR -P descrambler --aes-cbc e7b8e75466530c3cf7238f577e18618a -O file output.ts
tsp -I file 0000000100000002STR -P descrambler --aes-ctr e7b8e75466530c3cf7238f577e18618a -O file output.ts
tsp -I file 0000000100000002STR -P descrambler --atis-idsa e7b8e75466530c3cf7238f577e18618a -O file output.ts
sp -I file 0000000100000002STR -P descrambler --dvb-cissa e7b8e75466530c3cf7238f577e18618a -O file output.ts
I tried these but the resulting file still contains passwords because it cannot be read.

**Comment by atplsx** [comment]
extracted mpeg-ts analyse
===============================================================================
|  TRANSPORT STREAM ANALYSIS REPORT                                           |
|=============================================================================|
|  Transport Stream Id: ...... 43104 (0xA860)  |  Services: .............. 2  |
|  Bytes: ....................... 298,057,268  |  PID's: Total: ......... 12  |
|  TS packets: .................... 1,585,411  |         Clear: .......... 6  |
|     With invalid sync: .......... 1,546,332  |         Scrambled: ...... 6  |
|     With transport error: ......... 776,722  |         With PCR's: ..... 4  |
|     Suspect and ignored: ............ 3,705  |         Unreferenced: ... 6  |
|-----------------------------------------------------------------------------|
|  Transport stream bitrate, based on ....... 188 bytes/pkt    204 bytes/pkt  |
|  User-specified: ................................... None             None  |
|  Estimated based on PCR's: ...................... Unknown          Unknown  |
|  Selected reference bitrate: .................... Unknown             None  |
|-----------------------------------------------------------------------------|
|  Broadcast time: ................................................. Unknown  |
|-----------------------------------------------------------------------------|
|  Srv Id  Service Name                              Access          Bitrate  |
|  0x0001  (unknown) .................................... C          Unknown  |
|  0x3FAC  (unknown) .................................... S          Unknown  |
|                                                                             |
|  Note 1: C=Clear, S=Scrambled                                               |
|  Note 2: Unless specified otherwise, bitrates are based on 188 bytes/pkt    |
===============================================================================


===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 27, PID's: 1 (clear: 1, scrambled: 0)                          |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C          Unknown  |
|   Subt.  Global PSI/SI PID's (0x00-0x1F) .............. C          Unknown  |
|  0x0000  PAT .......................................... C          Unknown  |
|=============================================================================|
|  Unreferenced PID's                                                         |
|  TS packets: 6, PID's: 6 (clear: 1, scrambled: 5)                           |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Unreferenced PID's ........................... S          Unknown  |
|  0x02EA  Unreferenced ................................. S          Unknown  |
|  0x0BC9  Unreferenced ................................. S          Unknown  |
|  0x0C5B  Unreferenced ................................. S          Unknown  |
|  0x0DCD  Unreferenced ................................. C          Unknown  |
|  0x0EDB  Unreferenced ................................. S          Unknown  |
|  0x1613  Unreferenced ................................. S          Unknown  |
|=============================================================================|
|  Service: 0x0001 (1), TS: 0xA860 (43104), Original Netw: 0x0000 (0)         |
|  Service name: (unknown), provider: (unknown)                               |
|  Service type: 0x00 (Undefined)                                             |
|  TS packets: 1, PID's: 2 (clear: 2, scrambled: 0)                           |
|  PMT PID: 0x00B1 (177), PCR PID: 0x1F00 (7936)                              |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Undefined .................................... C          Unknown  |
|  0x00B1  PMT .......................................... C          Unknown  |
|  0x1F00  MPEG-2 Audio ................................. C          Unknown  |
|          (C=Clear, S=Scrambled, +=Shared)                                   |
|=============================================================================|
|  Service: 0x3FAC (16300), TS: 0xA860 (43104), Original Netw: 0x0000 (0)     |
|  Service name: (unknown), provider: (unknown)                               |
|  Service type: 0x00 (Undefined)                                             |
|  TS packets: 32,315, PID's: 4 (clear: 3, scrambled: 1)                      |
|  PMT PID: 0x1293 (4755), PCR PID: 0x12F7 (4855)                             |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Undefined .................................... S          Unknown  |
|  0x1293  PMT .......................................... C          Unknown  |
|  0x12F7  HEVC video ................................... C          Unknown  |
|  0x135B  E-AC-3 Audio (tur) ........................... C          Unknown  |
|  0x13BF  MPEG-2 AAC Audio (tur) ....................... S          Unknown  |
|          (C=Clear, S=Scrambled, +=Shared)                                   |
===============================================================================


===============================================================================
|  PIDS ANALYSIS REPORT                                                       |
|=============================================================================|
|  PID: 0x0000 (0)                                                       PAT  |
|-----------------------------------------------------------------------------|
|  Global PID                Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............ 27  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ........ 26  |
|                            Duplicated: .......... 0  Sections:              |
|                                                      Unit start: ...... 26  |
|=============================================================================|
|  PID: 0x00B1 (177)                                                     PMT  |
|  Service: 0x0001 (1) (unknown)                                              |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|                            Duplicated: .......... 0  Sections:              |
|                                                      Unit start: ....... 1  |
|=============================================================================|
|  PID: 0x02EA (746)                                            Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 1  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ......... 1                            Unit start: ....... 1  |
|  Clock values range:                                                        |
|  PCR: ................. 1                                                   |
|  from . 1,855,544,238,728                                                   |
|  to ... 1,855,544,238,728                                                   |
|  Leaps: ............... 0                                                   |
|=============================================================================|
|  PID: 0x0BC9 (3017)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 1  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ......... 0                            Unit start: ....... 0  |
|  Clock values range:                                                        |
|  PCR: ................. 1                                                   |
|  from .... 41,858,928,755                                                   |
|  to ...... 41,858,928,755                                                   |
|  Leaps: ............... 0                                                   |
|=============================================================================|
|  PID: 0x0C5B (3163)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ......... 0                            Unit start: ....... 1  |
|=============================================================================|
|  PID: 0x0DCD (3533)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|                            Duplicated: .......... 0  Sections:              |
|                                                      Unit start: ....... 0  |
|=============================================================================|
|  PID: 0x0EDB (3803)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ......... 0                            Unit start: ....... 0  |
|=============================================================================|
|  PID: 0x1293 (4755)                                                    PMT  |
|  Service: 0x3FAC (16300) (unknown)                                          |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............ 31  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ........ 29  |
|                            Duplicated: .......... 1  Sections:              |
|                                                      Unit start: ...... 31  |
|=============================================================================|
|  PID: 0x12F7 (4855)                                             HEVC video  |
|  PES stream id: 0xE0 (Video 0)                                              |
|  Service: 0x3FAC (16300) (unknown)                                          |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ........ 31,901  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: .......... 172  Unexpect: .... 31,900  |
|                            Duplicated: .......... 0  PES:                   |
|                                                      Packets: ......... 84  |
|                                                      Inv.Start: ........ 0  |
|  Clock values range:                                                        |
|  PCR: ................ 71  PTS: ................ 84  DTS: ............. 77  |
|  from . 1,294,572,264,134  from ..... 4,315,057,632  from .. 4,315,052,232  |
|  to ... 1,296,848,711,401  to ....... 4,322,950,632  to .... 4,322,947,032  |
|  Leaps: .............. 35  Leaps: ............... 3  Leaps: ............ 5  |
|=============================================================================|
|  PID: 0x135B (4955)                                     E-AC-3 Audio (tur)  |
|  PES stream id: 0xBD (Private stream 1)                                     |
|  Service: 0x3FAC (16300) (unknown)                                          |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ........... 293  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 2  Unexpect: ....... 253  |
|                            Duplicated: ......... 18  PES:                   |
|                                                      Packets: .......... 9  |
|                                                      Inv.Start: ........ 0  |
|  Clock values range:                                                        |
|                            PTS: ................. 9                         |
|                            from ..... 4,315,916,862                         |
|                            to ....... 4,321,982,142                         |
|                            Leaps: ............... 6                         |
|=============================================================================|
|  PID: 0x13BF (5055)                                 MPEG-2 AAC Audio (tur)  |
|  PES stream id: 0xC0 (Audio 0)                                              |
|  Service: 0x3FAC (16300) (unknown)                                          |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............ 90  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 9  Unexpect: ........ 84  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 1  PES:                   |
|  Inv.scramb.: ......... 0                            Packets: ......... 12  |
|                                                      Inv.Start: ........ 0  |
|  Clock values range:                                                        |
|                            PTS: ................ 12                         |
|                            from ..... 4,317,491,712                         |
|                            to ....... 4,322,554,752                         |
|                            Leaps: ............... 5                         |
|=============================================================================|
|  PID: 0x1613 (5651)                                           Unreferenced  |
|-----------------------------------------------------------------------------|
|  Unreferenced PID          Transport:                Discontinuities:       |
|  Bitrate: ....... Unknown  Packets: ............. 1  Expected: ......... 0  |
|  Access: ...... Scrambled  Adapt.F.: ............ 1  Unexpect: ......... 0  |
|  Crypto-Per: .... Unknown  Duplicated: .......... 0  Sections:              |
|  Inv.scramb.: ......... 0                            Unit start: ....... 0  |
|  Clock values range:                                                        |
|  PCR: ................. 1                                                   |
|  from . 1,958,103,213,586                                                   |
|  to ... 1,958,103,213,586                                                   |
|  Leaps: ............... 0                                                   |
===============================================================================


===============================================================================
|  TABLES & SECTIONS ANALYSIS REPORT                                          |
|=============================================================================|
|  PID: 0x0000 (0)                                                       PAT  |
|-----------------------------------------------------------------------------|
|  0x00 (0, PAT), TID ext: 0x0006 (6)                                         |
|      Repetition: ...... 0  pkt  Section cnt: ........ 1                     |
|      Min repet.: ...... 0  pkt  Table cnt: .......... 1                     |
|      Max repet.: ...... 0  pkt  Version: ............ 3                     |
|-----------------------------------------------------------------------------|
|  0x00 (0, PAT), TID ext: 0xA860 (43104)                                     |
|      Repetition: .. 57652  pkt  Section cnt: ....... 25                     |
|      Min repet.: ... 2448  pkt  Table cnt: ......... 25                     |
|      Max repet.: . 216480  pkt  Version: ............ 1                     |
|=============================================================================|
|  PID: 0x00B1 (177)                                                     PMT  |
|  Service: 0x0001 (1) (unknown)                                              |
|-----------------------------------------------------------------------------|
|  0x02 (2, PMT), TID ext: 0x0001 (1)                                         |
|      Repetition: ...... 0  pkt  Section cnt: ........ 1                     |
|      Min repet.: ...... 0  pkt  Table cnt: .......... 1                     |
|      Max repet.: ...... 0  pkt  Version: ............ 0                     |
|=============================================================================|
|  PID: 0x1293 (4755)                                                    PMT  |
|  Service: 0x3FAC (16300) (unknown)                                          |
|-----------------------------------------------------------------------------|
|  0x02 (2, PMT), TID ext: 0x3FAC (16300)                                     |
|      Repetition: .. 45204  pkt  Section cnt: ....... 28                     |
|      Min repet.: ... 3984  pkt  Table cnt: ......... 28                     |
|      Max repet.: . 260304  pkt  Version: ............ 9                     |
===============================================================================
