### ISSUE TITLE
[BUG] Wrong Service Type Name with Analyze Plugin

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1334]
#### Bug description:
plugin analyze output -> "service" object reports wrong service_type name:

`{
			"bitrate": 7130628,
			"bitrate-204": 7737490,
			"components": {
				"clear": 4,
				"scrambled": 3,
				"total": 7
			},
			"id": 116,
			"is-scrambled": true,
			"name": "Service Test"
			"original-network-id": 133,
			"packets": 14449,
			"pcr-pid": 767,
			"pids": [
				98,
				767,
				771,
				772,
				6803,
				7059,
				7315
			],
			"pmt-pid": 98,
			"provider": "TEST"
			"ssu": false,
			"t2mi": false,
			"tsid": 9,
			"type": 25,
			"type-name": "MetaData in DSM-CC Sync. Download Protocol"
		}`

#### How to reproduce:
Analyze a TS with plugin analyze

#### Expected behavior:
service_type:25 should be "Advanced codec HD digital television service" and not 

#### Environment:
 - OS: Windows
 - OS version:  0
 - TSDuck full version: 3.36-3347
 - Installation type: official binary

**Comment by lelegard** [comment]
Hi @enricovittorini 

Thanks for reporting this. There is a bug, indeed, in the JSON analysis report (other formats are correct).

A very silly bug: calling function `names::StreamType()` instead of `names::ServiceType()` during the generation of the JSON report. I will fix it.
