### ISSUE TITLE
[Q] regarding remote control 

### ISSUE THREAD

**Issue by jangrayogesh** [tsduck/tsduck#1343]
i am unable to establish the connection for the remote control like i am unable to send the commands to udp port 4444
can someone help me with that or you can provide me the code for tsswitch for 2-3 file and i can send the control using udp.

error:
tsswitch -v --remote 4444 -f --event-command "echo ==== EVENT" --event-udp 192.168.29.101:4444 -I file tssample.ts -I file ts.ts -I file video1.ts -I file ts.ts | tsp -P regulate -O ip 127.0.0.1:1234
* Error: socket option SO_TIMESTAMPNS: Protocol not available

I will be thankful for that.

**Comment by lelegard** [comment]
Hi @jangrayogesh 

Please provide more details. Which operating system? Which distro? Which version? Which TSDuck version?

**Comment by jangrayogesh** [comment]
i have solved this but i want to ask one more question 
can i add ts files while executing the tsswitch command?

**Comment by lelegard** [comment]
If the question is "can we add a new input plugin on the fly to tsswitch, without stopping and restarting it", the answer is no.
