### ISSUE TITLE
[Q] tsduck live probe

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1351]
hello @lelegard, 
i would like to build a live probe with tsduck. I am not a developer but jsut trying to implement something with some coding. 
I would like to mention in my code that it is powered by tsduck. I am adding in the HTML footer a "credits" link that shows a modal with the links to tsduck website and license:

![image](https://github.com/tsduck/tsduck/assets/36230446/0951c82d-20fd-4f1c-b533-b3cd84505e77)

![image](https://github.com/tsduck/tsduck/assets/36230446/7566b13e-41d2-4377-9436-446578d98f7b)

just wanted to check with you if this is fine for you.

thanks

**Comment by lelegard** [comment]
I see why you needed more detailed SRT stats 😉

> just wanted to check with you if this is fine for you.

No problem at all. I carefully selected a very liberal license to allow the reuse of TSDuck in all circumstances. I hate restrictive licenses such as GPL which are compatible with virtually nothing except themselves. 

The BSD license is very simple. Just follow the two clauses, basically meaning you just have to mention the original TSDuck copyright text. As an example, the file `OTHERS.txt` in TSDuck contains the copyright of other libraries which are used by TSDuck. 

It looks like a nice tool. If it's useful to you, it may be useful to others (which is the story of TSDuck). I can only encourage you to publish it as open source.

**Comment by EvariSTC** [comment]
@enricovittorini  please keep us updated

**Comment by enricovittorini** [comment]
@EvariSTC I am progressing step by step... I am not a developer but trying to build something nice.

Things are progressing... 

![image](https://github.com/tsduck/tsduck/assets/36230446/131ae71d-4e70-4106-9cd4-73ed072e8938)
