### ISSUE TITLE
[Q] Analyze Plugin  pes-stream-id forTeletext

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1360]
When PES carries Teletext, am i wrong or the pes-stream-type at the output of "analyze" plugin should be private_stream_1?

**Comment by lelegard** [comment]
The plugin analyze outputs what the stream contains. Looking at some streams in the [repository](https://tsduck.io/streams/), Teletext streams have private 1 as stream id, indeed. I do not know if other values are valid or not.

**Comment by enricovittorini** [comment]
I think the issue was a txt PID declared but with 0 bps.

**Comment by lelegard** [comment]
> I think the issue was a txt PID declared but with 0 bps.

The stream id is extracted from the PES header, it cannot be found in the signalisation. So, indeed, 0 pbs = 0 packet = unknown stream id.

**Comment by enricovittorini** [comment]
Yes of course. Didn't notices there were 0 packets is that PID. Sorry...
