### ISSUE TITLE
[FEAT] bitrate_monitor add json-line

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1379]
It would be great to add the JSON line output format for the bitrate monitor plugin.

Possibly in addition to the total TS and Net bitrate would be great to attnthe stuffing bitrate

**Comment by lelegard** [comment]
> It would be great to add the JSON line output format for the bitrate monitor plugin.

That should be easy.

> Possibly in addition to the total TS and Net bitrate would be great to attnthe stuffing bitrate

The stuffing bitrate is simply the total minus net bitrate. Seems redundant, isn't it?

**Comment by enricovittorini** [comment]
thanks @lelegard, I agree regarding the stuffing, but was just to have something complete at the output. As you prefer, in my case would not be be an issues to do the math in my code instead of accessing the key value.

**Comment by lelegard** [comment]
Option `--json-line` added.

**Comment by enricovittorini** [comment]
thanks @lelegard

**Comment by enricovittorini** [comment]
hello @lelegard, would it be possible to implement also the json-line for the continuity plugin?

**Comment by lelegard** [comment]
> would it be possible to implement also the json-line for the continuity plugin?

Done
