### ISSUE TITLE
[Q] Filter plugin --> analyze plugin: missing description

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1381]
I am trying the following command:

`tsp -I  ip 239.0.0.1:5555 -l 10.0.0.100 -P filter --service 40  -P tables   -i 5 -O drop`

The description value of the analyze.pid reports "Unreferenced". Would like to understand if this is expected as if i remove the Filter plugin i can get the correct description of the coded

`{ "pids": [ { "audio": false, "bitrate": 4855, "bitrate-204": 5268, "description": "Unreferenced", "ecm": false, "emm": false, "global": true, "id": 100, "is-scrambled": false, "packets": { "af": 0, "clear": 5, "discontinuities": 0, "dts": 0, "dts-leap": 0, "duplicated": 0, "invalid-scrambling": 0, "pcr": 0, "pcr-leap": 0, "pts": 0, "pts-leap": 0, "scrambled": 0, "total": 5 }, "pmt": false, "service-count": 0, "t2mi": false, "unit-start": 5, "unreferenced": true, "video": false }, { "audio": false, "bitrate": 2035227, "bitrate-204": 2208437, "description": "Unreferenced", "ecm": false, "emm": false, "first-dts": 4846971421, "first-pcr": 1454072431000, "first-pts": 4846989421, "global": true, "id": 101, "is-scrambled": false, "last-dts": 4847115421, "last-pcr": 1454113074337, "last-pts": 4847133421, "packets": { "af": 84, "clear": 2096, "discontinuities": 0, "dts": 36, "dts-leap": 0, "duplicated": 0, "invalid-scrambling": 0, "pcr": 44, "pcr-leap": 0, "pts": 41, "pts-leap": 0, "scrambled": 0, "total": 2096 }, "pes-stream-id": 224, "pmt": false, "service-count": 0, "t2mi": false, "unit-start": 41, "unreferenced": true, "video": false }, { "audio": false, "bitrate": 133028, "bitrate-204": 144349, "description": "Unreferenced", "ecm": false, "emm": false, "first-pts": 4846926480, "global": true, "id": 102, "is-scrambled": false, "last-pts": 4847043120, "packets": { "af": 14, "clear": 137, "discontinuities": 0, "dts": 0, "dts-leap": 0, "duplicated": 0, "invalid-scrambling": 0, "pcr": 0, "pcr-leap": 0, "pts": 7, "pts-leap": 0, "scrambled": 0, "total": 137 }, "pes-stream-id": 192, "pmt": false, "service-count": 0, "t2mi": false, "unit-start": 7, "unreferenced": true, "video": false } ], "time": { "local": { "system": { "first": { "date": "2023/12/12", "seconds-since-2000": 755731627, "time": "21:27:07.274" }, "last": { "date": "2023/12/12", "seconds-since-2000": 755731628, "time": "21:27:08.822" } } }, "utc": { "system": { "first": { "date": "2023/12/12", "seconds-since-2000": 755728027, "time": "20:27:07.274" }, "last": { "date": "2023/12/12", "seconds-since-2000": 755728028, "time": "20:27:08.822" } } } }, "ts": { "bitrate": 2173109, "bitrate-204": 2358055, "bytes": 420744, "duration": 1, "packets": { "invalid-syncs": 0, "suspect-ignored": 0, "total": 2238, "transport-errors": 0 }, "pcr-bitrate": 2173109, "pcr-bitrate-204": 2358055, "pids": { "clear": 3, "global": { "bitrate": 0, "bitrate-204": 0, "clear": 0, "is-scrambled": false, "packets": 0, "scrambled": 0, "total": 0 }, "pcr": 1, "scrambled": 0, "total": 3, "unreferenced": 3 }, "services": { "clear": 0, "scrambled": 0, "total": 0 }, "user-bitrate": 24882349, "user-bitrate-204": 26999996 } }`

**Comment by lelegard** [comment]
The expression `-P filter --service 40` _"select packets belonging to any of the specified services as PMT, component or ECM."_ This means that everything else, including the PAT is removed. The next analyze plugin does not receive a PAT, cannot locate the PMT's and the structure of the service. So, everything is "unreferenced".

You need to add in the filter enough PID's to identify the structure of the TS.

However, if your purpose is to keep only one service in a consistent TS, use the plugin `zap`. It recreates a consistent SPTS.
