### ISSUE TITLE
[Q] Clarification on analyze plugin output

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1391]
I did check in the manual but did not find explanation for the following parameters for the json-output of the analyze plugin (I did check the Normalized output format paragraph)

pids.packet: 
- af
- pcr-leap
- dts-leap
- pts leap
- discontinuities: is this cc-errr?

thanks

**Comment by lelegard** [comment]
- af = number of packets with an adaptation field in the header, not necessarily meaningful, just an information.
- pcr-leap, dts-leap, pts leap = "leap" in timestamps, meaning consecutive timestamps with suspect distance, typically more than a couple of seconds, probably a symptom of something going wrong. One exception: there is one expected leap every 26 hours when the integer value of the timestamps wraps down to zero.
- discontinuities = errors in continuity counters, a symptom of missing or incorrect packets.
