### ISSUE TITLE
[Q] compile new plugin only

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1394]
I am trying to understand how to compile a new plugin:
_Create a source file named tsplugin_foo.cpp in the tsplugins subdirectory._

How can I compile only a new plugin without recompiling the whole tsduck soruce code?

**Comment by lelegard** [comment]
You have to install the TSDuck "development environment". This is the package named tsduck-devel or tsduck-dev. The package named tsduck installs the binaries, tools and plugins only.

Alternatively, `make install` installs everything.

Once this is installed, the scripts or makefiles in the `sample` directory work.

This is the classical process for libraries: 1) developing the library 2) using the installed binary library to run an application, 3) developing an application using the installed headers and libraries.
