### ISSUE TITLE
tsscan without NIT

### ISSUE THREAD

**Issue by rezna11** [tsduck/tsduck#140]
Hello, I wanted to ask if `tsscan` can work without a valid NIT. If I try to scan a satellite, it fails to find anything because the frequency I use as the parameter for `tsscan` contains wrong NIT and no channels are found because of that.
Also, when I use a frequency which contains a NIT with frequencies of other providers, then the scanning finds many channels which I don't really care about, I just wanted to scan a single frequency.
So I just wanted to ask if this is how it's supposed to be and if I want to scan a single frequency, I should use `tsp` with some plugin to analyze the SDT and print the channels found...

**Comment by lelegard** [comment]
What about `tsp ... -P tables -p 0x11 -t 0x42 -x 1` ?

**Comment by lelegard** [comment]
Or, for a more user-friendly display:
~~~
tsp -I ... -P tables -p 0x11 -t 0x42 -x 1 -O drop | sed -e '/^ *Service:/!d' -e 's/^ *Service: "//' -e 's/".*//'
~~~

**Comment by rezna11** [comment]
yes, that's what I basically want to do and I was wondering if it's possible with `tsscan`

**Comment by lelegard** [comment]
`tsscan` emulates what a TV set or STB does when scanning a network.

What you want is slightly different and achievable using the plugin `tables`. Why would you like `tsscan` to do it instead ? We don't care about which tool we use as long as we obtain what we want.

**Comment by rezna11** [comment]
Well it was just a question. I spent some time wondering why `tsscan` looks for channels on some weird frequency. Then I found that there's NIT for another network (same provider but different satellite with different frequency). So I just wanted to ask what was the main purpose of `tsscan`  but it's now completely clear and I'm perfectly happy with the outcome :)
