### ISSUE TITLE
[Q] Is it possible to change PID number

### ISSUE THREAD

**Issue by jangrayogesh** [tsduck/tsduck#1422]
I want to ask that is it possible to change the PID for video according to our need like the original PID is 0x0100 and i want to change that to 0x0101 or 0x0111?

**Comment by lelegard** [comment]
Hi @jangrayogesh 

The plugin `remap` does this. In your case, this means `-P remap 0x0101=0x0111`. The relevant PMT will be updated accordingly. Please RTFM for more details.

**Comment by jangrayogesh** [comment]
Thank You
