### ISSUE TITLE
[Q] How can I Install from source code, and execute to check the results in python, 

### ISSUE THREAD

**Issue by debaditya22** [tsduck/tsduck#1433]
new to this so if anyone can guide me step by step it would be great .
Trying on Ubuntu 22.04, thanks.

**Comment by lelegard** [comment]
Hi @debaditya22 

General build instructions are here: https://tsduck.io/doxy/building.html

For a Ubuntu system, the simplest procedure is the following:
1. Get source code: `git clone https://github.com/tsduck/tsduck.git`
2. Install prerequisites for build: `tsduck/scripts/install-prerequisites.sh`
3. Build an installer: `make -C tsduck installer`
4. Collect the `.deb` packages in `tsduck/pkg/installers` and install them

There are a few sample Python programs in `tsduck/sample/sample-python`.

The Python module for TSDuck is installed in directory `/usr/share/tsduck/python`. You need to add it in your `PYTHONPATH` environment variable.

The general TSDuck library is designed for C++ applications. Only a high-level subset is available for Python and Java applications. Overview here: https://tsduck.io/doxy/jpbindings.html

Documentation of Python bindings here: https://tsduck.io/doxy/group__python.html
