### ISSUE TITLE
[Q] Add an ais service (HbbTV)

### ISSUE THREAD

**Issue by hofmeirmedia** [tsduck/tsduck#1435]
Hello,
is it possible to add an AIS service to an existing mpeg ts multicast with tsduck?

**Comment by lelegard** [comment]
Hi @hofmeirmedia 

TSDuck is able to insert data services. This is a low level scriptable toolset. It is ideal for automation, testing and debug. You need to understand the internals of the various protocols. If you are looking for some click-and-play GUI application which hides the technical details, TSDuck is probably not what you want. 

BTW, I do not know what "ais" means. 

First, you need to create the PMT and AIT of your service in XML or JSON form. If you need to cycle other data sections, prepare them is XML, JSON or binary form. 

In a `tsp` command, use the `pat` plugin to add a reference to your new data service. Use `inject` plugins to inject your PMT and AIT (and other sections if required). 

Be sure to have enough "free space" (ie. null packets) in your TS to replace with new inserted packets. In the case of a fixed bitrate broadcast TS, you need enough pre-existing stuffing. In the case of a VBR IP multicast TS without stuffing, use option `--add-input-stuffing` to create artificial free space. In that case, use a `filter` plugin at the end of the chain, just before the output plugin, to remove the unused stuffing. 

If you are not familiar with TSDuck already, the learning curve may be sharp. Be sure to browse through the user's guide. In the example chapter, there is a example of MPE service insertion which creates a service with PMT ant INT. Inserting a service with PMT ant AIT is simular.
