### ISSUE TITLE
[Q] TSAnalyze and metrics

### ISSUE THREAD

**Issue by mzbroch** [tsduck/tsduck#1437]
Hi! First - thanks for producing an awesome tool and documentation! I am looking for best practices around long-term collecting and storing the tsanalyze data produced by live IP input.

The first approach I took, was to use `tsp -I ip -r 192.168.1.1:2000 -P analyze -O drop`, which gives the total information at the end of measurement (program exit).
This can be changed by adding intreval `tsp -I ip -r 192.168.1.1:2000 -P analyze -i 1 -O drop`, which then gives the total information on each interval, and then zeroes counters, and starts counters again in next interval.

I would be interested to know is it possible to run the TSDuck infinitely and access tsanalyze counters programatically (so that they are not zeroed based on event (interval) ? 

some example pseudocode:
```
tsp = tsduck.TSProcessor()
tsp.input = ['ip', '-r', '192.168.1.1:2000']
tsp.plugins = [['analyze', '--json-line='+json_marker]]
tsp.output = ['drop']

with http_metrics_server as server:
    server.listen()
    server.serve_metrics(tsp["data"]["ts"]["packets"])
```

**Comment by mzbroch** [comment]
> If you want to receive a cumulative / incremental analysis (ie. not reset at each interval), then add options `--cumulative` and `--interval` in plugin `analyze`.
> If you want to query the counters at any possible time, without waiting for the interval, I do not see any solution for now.

Thank You! The cumulative option is what I was looking for!
May I ask You about long term collection - I see counters are 64bit integers, do they wrap up? However, I don't think it can be an issue with MPEG where I observe ~5k pps (157680000000 yearly)

**Comment by lelegard** [comment]
Using 64 bits without caring for overflow was planned from the very beginning. For instance, for a TS at 100 Mb/s, you can count bits (not packets, not bytes, _bits_) during 5849 years. And any event on a TS necessarily occurs less frequently than bits. So, I think you are safe...

**Comment by mzbroch** [comment]
Thank You for Your support!
