### ISSUE TITLE
[FEAT] documented "--version=all"

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#1439]
#### Is your feature request related to a problem?
Several times I need to execute the parameter `--version=all`. But it is not documented in the `--help`. And then I need to check the documentation to get it.

#### Proposed solution:
Please, @lelegard add one line inside the help printing about the `--version=all`.

#### Alternatives:
Search in the documentation... that is slow.

#### Additional information:
I've requested this several times. 😢

**Comment by lelegard** [comment]
Hi @lars18th 

I may consider it.

Other alternative is to provide an incorrect value to get the list of valid ones:
~~~
$ tsp --version=x
tsp: invalid value x for option --version, use one of "acceleration", "all", "bitrate", "compiler", "date", "dektec", "http", "integer", "long", "nsis", "rist", "short", "srt", "system", "vatek"
~~~

Not everything from the 580 pages of the user's guide can be in the help texts.

**Comment by lars18th** [comment]
> I may consider it.

Yes... please. But some simple as (part of current `tsp --help`):
```
  --version
      Display the TSDuck version number.
      (use version=all, or version=help for more info)
```

**Comment by lelegard** [comment]
Done (there was only one flag to remove)
~~~
  --version[=name]
      Display the TSDuck version number.
      The 'name' must be one of "acceleration", "all", "bitrate", "compiler",
      "crypto", "date", "dektec", "http", "integer", "long", "nsis", "rist",
      "short", "srt", "system", "vatek".
~~~

**Comment by lars18th** [comment]
Thank you @lelegard . I close the issue.
