### ISSUE TITLE
Question: Partial stop of TSAnalyze

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#145]
Hi @lelegard ,

I don't know you to _partially_ analyze a large TS file.

When using the `tsanalyze` tool, with the `<CTRL>+<C>` key the program stops, and it doesn't print the output info. Futhermore, I can't found any parameter to limit the reading to a N bytes or X seconds.

Any idea?
Thank you!

**Comment by lelegard** [comment]
~~~
tsp -I file foo.ts -P until --packets NNN -P analyze -O drop
~~~
