### ISSUE TITLE
[Q] Support for MacOS + Dektec devices

### ISSUE THREAD

**Issue by giorgos-epitropou-obs** [tsduck/tsduck#1450]
Hi, the question is pretty much what the title says.
I have a MacOS laptop (M1) and I want to ask if tsduck can run/support tsp commands with my DTU-315 usb Dektec modulator. Specifically, in the documentation it mentions that it is available via homebrew but also _"On macOS or unsupported Linux platforms (Alpine, Arm processors), TSDuck is automatically compiled with NODEKTEC set."_ Does that mean I have to compile it my self or it cannot support these devices at all. Also, if it does support it, do I need special drivers?
thank you

**Comment by lelegard** [comment]
Hi @giorgos-epitropou-obs 

The answer is unfortunately simple: Dektec (the company) does not support macOS. There is no macOS device driver and no DTAPI binary (the closed-source library to access Dektec devices).

This is a request for Dektec. However, they are focused on professional broadcast applications and I doubt that there is a significant demand for macOS here.
