### ISSUE TITLE
[FEAT] SRT Connection Bonding - Broadcast Mode

### ISSUE THREAD

**Issue by jace-23** [tsduck/tsduck#1458]
Hi Lelegard,

Hope you are well.

I am looking to implement a TSDuck instance using SRT Connection Bonding (link below). I did not see it in the TSDuck manual so was wondering if it were possible using TSDuck.

https://github.com/Haivision/srt/blob/master/docs/features/bonding-quick-start.md

I'm hoping to run 2 SRT connections from the one instance to send data over the internet (each SRT connection using a different network/public address), where the aim is to have these 2 feeds as 2022-7 compliant (seamless). We are hoping that this "SRT Connection Bonding" described in the link above could be a solution, where we would run the 2 SRT connections in "Broadcast" mode as described below:
_[Broadcast]-_ _In Broadcast mode, data is sent redundantly over all the member links in a group. If one of the links fails or experiences network jitter and/or packet loss, the missing data will be received over another link in the group. Redundant packets are simply discarded at the receiver side._

Would you be able to see if this is possible using TSDuck?

Thanks heaps

Kind Regards
Jace

**Comment by lelegard** [comment]
Hi @jace-23 

There is currently no support for SRT bonding in the `srt` input and output plugins.
