### ISSUE TITLE
zap and EPG

### ISSUE THREAD

**Issue by rezna11** [tsduck/tsduck#147]
Hello. I can't figure this one out - why is the EPG removed from the output if I do `zap`? Is this right? I can find another way to deal with this but maybe I'm missing something, so I'm just asking.

**Comment by rezna11** [comment]
It seems that this is how `zap` is supposed to behave. But wouldn't this be useful feature to keep EIT for the zapped channel? I mean, if `svremove` removes EIT for removed services, it would make sense for `zap` to work with EIT as well. But I guess it's not a problem to use `svremove` many times instead of one `zap` to solve this.

**Comment by rezna11** [comment]
Thanks, that's a good idea, similar to what I do now, which is forking PID 18 as local IP unicast and then merging it back after the `zap`. But there's still the issue with unnecessary EIT traffic from all the channels that were removed because of `zap` ... sure, adding `svremove` many times (for all removed channels, including other networks) would probably help so this isn't really such a big issue.

**Comment by lars18th** [comment]
Sure!

The `svremove` plugin has the functionality to discard the EPG data from the program to remove.

In any case, perhaps @lelegard will like to add the option inside `zap` to maintain the EIT pid with the data of only the zapped program.

Regards.

**Comment by rezna11** [comment]
Thanks! It looks good, comparing without and with `--eit`:
```

C:\>tsp -I file "D:\SAT\FULL TS\HBBTV\FRANSAT2.ts" -P zap 0x0606 -P eit -O drop
Summary
-------
TS id:         6 (0x0006)
Last UTC:      2018/06/15 19:47:36
EITp/f actual: 0
EITp/f other:  0
EITs actual:   0
EITs other:    0

TS      Services  With EITp/f  With EITs  EPG days
------  --------  -----------  ---------  --------
Actual         1            0          0         0
Other          0            0          0         0

A/O  TS Id   Srv Id  Name  EITp/f  EITs  EPG days
---  ------  ------  ----  ------  ----  --------
Act  0x0006  0x0606  TMC   no      no           0

C:\>tsp -I file "D:\SAT\FULL TS\HBBTV\FRANSAT2.ts" -P zap --eit 0x0606 -P eit -O drop
Summary
-------
TS id:         6 (0x0006)
Last UTC:      2018/06/15 19:47:36
EITp/f actual: 64
EITp/f other:  0
EITs actual:   137
EITs other:    0

TS      Services  With EITp/f  With EITs  EPG days
------  --------  -----------  ---------  --------
Actual         1            1          1         8
Other          0            0          0         0

A/O  TS Id   Srv Id  Name  EITp/f  EITs  EPG days
---  ------  ------  ----  ------  ----  --------
Act  0x0006  0x0606  TMC   yes     yes          8
```

**Comment by lelegard** [comment]
OK, good, closing this one then.
