### ISSUE TITLE
Splice injection dropped because pts obsolete.

### ISSUE THREAD

**Issue by jacksonvm** [tsduck/tsduck#153]
Hi @lelegard 

Lately I have been experimenting with the TSDUCK Splice inject plugin and I have been getting this error intermittently.

spliceinject: dropping SpliceInsert out @0x00E371320, start: 0x00E3194E0, end: 0x00E371320, 3 times, obsolete, current PTS: 0x00E3A0D0D
* spliceinject: dropping SpliceInsert out @0x00E371320, start: 0x00E3194E0, end: 0x00E371320, 3 times, obsolete, current PTS: 0x00E3A0D0D
* spliceinject: dropping SpliceInsert out @0x00E371320, start: 0x00E3194E0, end: 0x00E371320, 3 times, obsolete, current PTS: 0x00E3A0D0D 

Below is the command i'm using with TSP.

 tsp --debug -b 5500000 -I ip 224.6.6.6:4666 -P pmt --service 1 --add-programinfo-id 0x43554549 --add-pid 600/0x86 -P spliceinject --service 1 --inject-count 3 --start-delay 4000 --inject-interval 1000 --udp 4444 -O ip 224.7.7.7:4777 -l 192.168.2.235

This is a sample of the xml send to TSP, the XML's are send almost 1 to 2 min's prior.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<tsduck>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1" splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0xfd4d4b0">
<break_duration auto_return="False" duration="5400000"/>
</splice_insert>
</splice_information_table>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1" splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0xfd4d4b0">
<break_duration auto_return="False" duration="5400000"/>
</splice_insert>
</splice_information_table>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1" splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0xfd4d4b0">
<break_duration auto_return="False" duration="5400000"/>
</splice_insert>
</splice_information_table>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x10273a70">
</splice_insert>
</splice_information_table>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x10273a70">
</splice_insert>
</splice_information_table>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x10273a70">
</splice_insert>
</splice_information_table>
</tsduck>
```

Regards,

Jackson

**Comment by lelegard** [comment]
Hi,

Given the message, it seems that some intermittent cues are received too late.

What the message says is
- Received a cue information section for an event at PTS 0x00E371320 (=T0), supposed to be in the near future.
- First insertion scheduled at PTS = 0x00E3194E0 (T0 - 4s.)
- Last possible insertion at PTS = 0x00E371320 (T0)
- But current PTS in the video stream is 0x00E3A0D0D (T0 + 2.167 s.), _after_ the event.

The sample XML you provide looks OK but the PTS values are different. So, I assume that they are not the same events.

If the messages are intermittent only, you should investigate the injection system, I mean the system which sends the XML on UDP port 4444. From time to time, events are probably sent too late (here, 2 seconds _after_ the event instead of more than 4 seconds _before_ the event).

**Comment by jacksonvm** [comment]
Hi @lelegard ,

The XML's are send through udp well in advance to TSP (Like 60 to 120 Seconds). The issue is very intermittent , as you can see in the below logs, I will look into the code and see how i can print system time with the log. 

* spliceinject: requeueing SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10
* spliceinject: injecting SpliceInsert in @0x004336D10, start: 0x0042E9E98, end: 0x004336D10, 2 times, current PTS: 0x004317784
* spliceinject: requeueing SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10
* spliceinject: injecting SpliceInsert in @0x004336D10, start: 0x0042E9E98, end: 0x004336D10, 2 times, current PTS: 0x004317784
* spliceinject: requeueing SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10
* spliceinject: injecting SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10, current PTS: 0x004317784
* spliceinject: injecting SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10, current PTS: 0x004317784
* spliceinject: injecting SpliceInsert in @0x004336D10, start: 0x0042F4E60, end: 0x004336D10, current PTS: 0x004317784
* spliceinject: received message, 1453 bytes, from 127.0.0.1:44722
* spliceinject: enqueued SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times
* spliceinject: enqueued SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times
* spliceinject: enqueued SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times
* spliceinject: enqueued SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times
* spliceinject: enqueued SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times
* spliceinject: enqueued SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times




* spliceinject: dropping SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times, obsolete, current PTS: 0x008DEF95D
* spliceinject: dropping SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times, obsolete, current PTS: 0x008DEF95D
* spliceinject: dropping SpliceInsert out @0x008DC6060, start: 0x008D6E220, end: 0x008DC6060, 3 times, obsolete, current PTS: 0x008DEF95D
* spliceinject: received message, 1453 bytes, from 127.0.0.1:37542
* spliceinject: enqueued SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times
* spliceinject: enqueued SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times
* spliceinject: enqueued SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times
* spliceinject: enqueued SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times
* spliceinject: enqueued SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times
* spliceinject: enqueued SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009001500, end: 0x009059340, 3 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x00900C4C8, end: 0x009059340, 2 times, current PTS: 0x009042913
* spliceinject: requeueing SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340, current PTS: 0x009042A21
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340, current PTS: 0x009042A21
* spliceinject: injecting SpliceInsert in @0x009059340, start: 0x009017490, end: 0x009059340, current PTS: 0x009042A21
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times, current PTS: 0x00929AE40
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times, current PTS: 0x00929AE40
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x009299C40, end: 0x0092F1A80, 3 times, current PTS: 0x00929AE40
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times, current PTS: 0x0092A74C5
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times, current PTS: 0x0092A74C5
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092A4C08, end: 0x0092F1A80, 2 times, current PTS: 0x0092A74C5
* spliceinject: requeueing SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80, current PTS: 0x0092B2C02
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80, current PTS: 0x0092B2C02
* spliceinject: injecting SpliceInsert out @0x0092F1A80, start: 0x0092AFBD0, end: 0x0092F1A80, current PTS: 0x0092B2C02
* spliceinject: dropping SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times, obsolete, current PTS: 0x009586E13
* spliceinject: dropping SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times, obsolete, current PTS: 0x009586E13
* spliceinject: dropping SpliceInsert in @0x009584D60, start: 0x00952CF20, end: 0x009584D60, 3 times, obsolete, current PTS: 0x009586E13


Regards,

Jackson

**Comment by lelegard** [comment]
You can use `tsp --timed-log` to get a time stamp for each message. If you can do the same on the sending system, you will be able to correlate the two.

**Comment by jacksonvm** [comment]
Thanks @lelegard 

Please find the log below timestamps. 

tsp --timed-log -v -b 5500000 -I ip 224.6.6.6:4666  -P pmt --service 1 --add-programinfo-id 0x43554549 --add-pid
600/0x86 -P spliceinject --service 1 --inject-count 3 --start-delay 4000 --inject-interval 500 --udp 4444  -P pcrbitrate -P regulate -p 7 -O ip
224.7.7.7:4777 -l 192.168.2.235
* 2018/11/02 17:49:42 - regulate: minimum packet burst duration is 10,000,000 nano-seconds
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 172.16.10.159
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 172.17.0.1
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 192.168.25.235
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 192.168.33.210                                            |
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 202.191.166.9                                             |
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 192.168.37.210
* 2018/11/02 17:49:42 - ip: joining multicast group 224.6.6.6:4666 from local address 192.168.2.235

* 2018/11/02 17:51:02 - ip: input bitrate is 5,500,000 b/s
* 2018/11/02 17:51:02 - pmt: found service id 0x0001 (1), PMT PID is 0x1000 (4096)
* 2018/11/02 17:51:02 - pmt: PMT version 0 modified
* 2018/11/02 17:51:02 - spliceinject: found service id 0x0001 (1), PMT PID is 0x1000 (4096)
* 2018/11/02 17:51:02 - regulate: regulated at bitrate 5,500,000 b/s
* 2018/11/02 17:51:03 - pcrbitrate: new bitrate from PCR analysis: 5,499,999 b/s
* 2018/11/02 17:51:03 - regulate: regulated at bitrate 5,499,999 b/s
* 2018/11/02 17:51:27 - spliceinject: received message, 1453 bytes, from 127.0.0.1:58007
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times
* 2018/11/02 17:51:27 - spliceinject: enqueued SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times


* 2018/11/02 17:54:12 - spliceinject: dropping SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times, obsolete, current P
TS: 0x001057847
* 2018/11/02 17:54:12 - spliceinject: dropping SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times, obsolete, current P
TS: 0x001057847
* 2018/11/02 17:54:12 - spliceinject: dropping SpliceInsert out @0x00100AB80, start: 0x000FB2D40, end: 0x00100AB80, 3 times, obsolete, current P
TS: 0x001057847
* 2018/11/02 17:54:38 - spliceinject: dropping SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times, obsolete, current PT
S: 0x0012A7E2B
* 2018/11/02 17:54:38 - spliceinject: dropping SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times, obsolete, current PT
S: 0x0012A7E2B
* 2018/11/02 17:54:38 - spliceinject: dropping SpliceInsert in @0x00129DE60, start: 0x001246020, end: 0x00129DE60, 3 times, obsolete, current PT
S: 0x0012A7E2B

Log from the Injector.

./sh insert.sh 17:54:00:00 30 Fri Nov  2 17:51:27 IST 2018 Fri Nov  2 17:51:27 IST 2018 Fri Nov  2 17:51:27 IST 2018 Fri Nov  2 17:51:27 IST 2018
CURRTIME=17:51:27:13
CURRPTS=2421120
SCTETIME=17:54:00:00
SCTEPTS=16821120

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tsduck>
<splice_information_table>
<splice_insert splice_event_id="1073743324" unique_program_id="1" 
splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0x100ab80"> <break_duration auto_return="False" duration="2700000"/> </splice_insert> </splice_information_table> <splice_information_table> <splice_insert splice_event_id="1073743324" unique_program_id="1" 
splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0x100ab80"> <break_duration auto_return="False" duration="2700000"/> </splice_insert> </splice_information_table> <splice_information_table> <splice_insert splice_event_id="1073743324" unique_program_id="1" 
splice_event_cancel="false" avail_num="17"
out_of_network="true" pts_time="0x100ab80"> <break_duration auto_return="False" duration="2700000"/> </splice_insert> </splice_information_table> <splice_information_table> <splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x129de60"> </splice_insert> </splice_information_table> <splice_information_table> <splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x129de60"> </splice_insert> </splice_information_table> <splice_information_table> <splice_insert splice_event_id="1073743324" unique_program_id="1"
out_of_network="false" pts_time="0x129de60"> </splice_insert> </splice_information_table> </tsduck>
```

**Comment by lelegard** [comment]
OK, so the injector sends 6 events at 17:51:27. The plugin `spliceinject` receives and enqueues all of them at the same time (within the same second). But the 6 events are considered for insertion in the stream only at 17:54:38, 3 minutes later, at a time where the commands are obsolete.

My guess is the lack of input null packets. Have a look at the TSDuck user's guide, `tsp` reference documentation, section named _"Modifying, inserting and deleting packets"_. To _insert_ packets in a stream, `tsp` cannot create new packets. It can only replace null packets with inserted data. If the input stream does not contain any null packet, you cannot insert anything. In broadcast streams, with a fixed bitrate by design, there are always some or many null packets. On IP streams, mostly SPTS, there are usually no null packets. This is probably the case of your stream. After 3 minutes, there is probably one null packet for some reason. This is the first time `tsp` has the opportunity to insert something. But too late...

To solve the problem of inserting data in streams without null packets, you should artificially insert null packets before the input plugin (option `--add-input-stuffing`), giving space for insertion, and then removing the remaining stuffing just before the output plugin.

Your command would look like:
~~~
tsp --timed-log -v --add-input-stuffing 1/10 \
    -I ip ... \
    ... \
    -P spliceinject ... \
    -P filter --negate --pid 0x1FFF \
    -P pcrbitrate \
    -P regulate ... \
    -O ip ...
~~~

**Comment by jacksonvm** [comment]
Thank you @lelegard I think you have resolved the issue. By adding --add-input-stuffing 1/10 i havent PTS going obsolete yet.

Thanks and Lot. 

Regards,

Jackson
