### ISSUE TITLE
BUG: plugin ENCAP doubles bitrate

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#157]
Hi @lelegard ,

Last days I initiated a deep testing of the `encap`/`decap` plugins. And I found a bug:

- The `encap` plugin doesn't does the task described in the documentation, and commented in #126 .
- At time, the plugin is _doubling_ the number of input packets. In fact, it generates all the time **two** packets for each input packet. The result is one packet with payload only, with the next packet with the adaptation field set with 180 bytes size (and mainly empty with zeroes) with the remaining bytes of the original packet as payload.
- So you see: Input={A...AAA....AA....} encapsulated to Output={A'A''...A'A''A'A''A'A''....A'A''A'A''....}.

Please, can you check the algoritm?

**Comment by lars18th** [comment]
Hi @lelegard ,

Your explanation is crystal clear!
Thank you for your support. I'll test it.

Regards.

**Comment by lars18th** [comment]
> Please, pull, rebuild and tell us if option --pack fits your needs.

Hi @lelegard ,

I see some strange results using the `--pack` option!

First of all, I need to say that I'm using (at time) the `encap` filter to pack PSI/SI tables. So my current command is `tsp ... -P duplicate 0-21=600 -P encap -p 600-621 -o 622 --pack ...`

So, adding the option `--pack` nearly all output packets have PUSI set. I feel this a bug, as I understand that only the _first_ packet of a "pack" needs to have the start indicator set to 1; while the rest doesn't have it. Right?

Futhermore, it's strange that the **first** output (outher) packet of the pack, instead of having as payload the content of **one** inner packet it has parts of **two** inner packets. My understanding is that the first output will have the first inner packet, except the last 4 bytes that have no space in the packet. Right?

Besides these problems (please review the code), I have a suggestion: Your first implementation without the `--pack` option seems to be the smartest strategy. However, it fails when the original stream is mulplitexed. In this case, it's common to have "holes" between packets with the same pid. Then, if some NULLs are in between of two sequential packets of the same pid, but they aren't adjancent, then an additional packet is allocated. That's the case where the `--pack` option has sense. However, I feel it's good not to put together packets that are far away.

So I suggest to add the concept of _distance_ in between for the parameter `--pack`. As example: `--pack 64` will indicate a _maximum_ number of 64 foreign consecutive packets before force to close the "pack" and flush the remaining buffer. See this example:

`.....A...A.A.............................A.A..A..A..AAAA.......`

Then with `--pack 8` it will be:

`.....P...p.p.......p.....................P.p..p..p..ppppp.......`

Hehe the `P` is the encapsulated (outer) packet that starts a group (PUSI=1), and `p` are the rest.
So the first three inner A packets will be in a group of four outer packets, and the other eight in another pack group.

I hope you take the idea.
Regards.

**Comment by lelegard** [comment]
It is normal that all outer packets which contain the start of an inner packet have PUSI set. This is done on purpose to be resilient to packet loss. This has been invented 20 years ago by MPEG engineers for section packetization and has proven to be robust and efficient.

About the idea of _distance_, I will think about it. There are many related questions to be solved.

About encapsulating PSI and services (after duplicating the PSI), which is your original idea, I implemented it in `test-035` of the TSDuck non-regression test suite (see https://github.com/tsduck/tsduck-test). You may have a look. The encapsulated and decapsulated streams are part of the reference data in the test suite.

**Comment by lars18th** [comment]
Hi @lelegard ,

Thank you for your response.

> It is normal that all outer packets which contain the start of an inner packet have PUSI set.

Then I've misunderstood the protocol. I feel the PUSI is set _only_ when a new"pack" starts. That's when the buffer is empty and a new inner packet comes.

In any case, why you then use the PUSI flag? From my understanding it's impossible to have one outer packet without the start of a inner packet... except in the case of an end packet (residual bytes).

> About the idea of distance, I will think about it. There are many related questions to be solved.

I feel is quite simple: add one additional counter that increments when a new packet comes and is not in the list for encapsulate. Then, for each output packet the counter is reseted. And when the counter rebases the distance, then a flush is executed (aka, close the "pack") and another reset of the distance counter.

What more I'm missing?

> About encapsulating PSI and services (after duplicating the PSI), which is your original idea, I implemented it in test-035 of the TSDuck non-regression test suite (see https://github.com/tsduck/tsduck-test). You may have a look. The encapsulated and decapsulated streams are part of the reference data in the test suite.

Thank you. It's interesting. But my objective is to preserva _all_ PSI/SI data _before_ the processing. So, first I add some NULL stuff, then I duplicate all 0x00-0x16, and I encapsulate it in a private pid. Only _after_ I remove all unused programs, I add the private pid to the target program, and I send all to the "processor".

In this user case, I still have some troubles with the encapsulation. So, for this reason I ask for the "distance" parameter.

**Comment by lelegard** [comment]
> In any case, why you then use the PUSI flag?

The PUSI is used to indicate the presence of the pointer field in the first byte of the payload. The pointer field is the important information, not the PUSI itself (it is just a trigger). Without PUSI, there is no pointer field. Again, this is exactly the same as specified in ISO 13818-1 for section packetization. Just replace the word "section" by "packet" and it is exactly the same. I did not reinvent the wheel. And I will not reinvent it, meaning I will not change this. 

> From my understanding it's impossible to have one outer packet without the start of a inner packet... except in the case of an end packet (residual bytes).

Without PUSI (and consequently without pointer field), the size of the payload is either 184 or 178 (with a PCR in the outer packet). Each encapsulated packet is 187 bytes long. So, there are cases where an inner packet is split over three outer packets. The middle outer packet has no PUSI, no start and no end of inner packet.

**Comment by lars18th** [comment]
Great explanation!
Thank you for sharing your knowledge with us.
