### ISSUE TITLE
CAP insert

### ISSUE THREAD

**Issue by tearepa13** [tsduck/tsduck#159]
For an in-house MATV with dozens of DVB-T channels (eg mining camp) requiring a common-alerting-protocol (xml) message insert eg "Cyclone alert go to the nearest shelter" would I be able to use DuckTS to do this ? I assume I would need to demod the input RF and somehow manipulate the stream above then encode and modulate back onto the same RF carrier freq? I'm no expert, but wondering if any sharp minds have their views?

**Comment by lelegard** [comment]
If the data to insert is some section with proper signalisation, it is certainly possible.

If you want to generate video or forced-OSD, this is more difficult with TSDuck alone. With the cooperation of additional tools such as FFmpeg, you can probably do something. Some people use a combination of TSDuck and FFmpeg to build audio/video TV processing systems.

I am more worried about non-technical issues, such as responsibilities. TSDuck was designed as a lab, testing, debug, demo tool. Although it has proven to be robust over years, relying on it for emergency alert systems like the one you described, where a system failure could be responsible for the loss of human lives, is a bit daring. Any system which is built around TSDuck is usually made of scripts. The scripts implement the application logic, relying on TSDuck for the transport stream plumbing. What if your script fails, the alert message not being displayed, people being killed for not rushing into shelters and their relatives suing you for being responsible ?
