### ISSUE TITLE
How to binary compare pids with "tscmp"?

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#170]
Hi @lelegard ,

In order to binary check `encap` and `decap` operations, with other processing in between, I need to compare **only** explicit pids from two files. In the `tscmp` I don't see any parameter to limit for specific pids.

Any ideas?
Regards.

**Comment by lelegard** [comment]
I suggest the same method as [test-035](https://github.com/tsduck/tsduck-test/blob/master/tests/test-035.sh) in the test suite: use `tsp -I file ... -P filter ... -O file...` on each file to extract only the target PIDs and then use `tscmp`.
