### ISSUE TITLE
Consistent TSDuck Binary, User Guide and Release Note Versions

### ISSUE THREAD

**Issue by paretech** [tsduck/tsduck#183]
The TSDuck Binary Download, User Guide and Release each show different versions. Expected outcome would be for download and documentation versions to match and for release history to match download history (i.e. older versions). 

The following table provides example as presented 2018-12-20.

Location | Version(s) Presented
-|-
https://tsduck.io/download/docs/tsduck.pdf | 3.16-1051
https://tsduck.io/download/changelog/ | 3.16-1065 (latest), 3.15-1007 (previous)
https://github.com/tsduck/tsduck/releases | 3.15-1008 (latest)
https://tsduck.io/download/tsduck/ | 3.15-1008

**Comment by lelegard** [comment]
Hi @paretech 

You are absolutely right. If TSDuck were a commercial product with proper QA, this would not be acceptable.

However, TSDuck is free open-source software where the sum of all teams, planning, architecture, design, developement, integration, technical writing, [QA](https://github.com/tsduck/tsduck-test/blob/master/README.md), delivery, web communication and support, is exactly _one_ single person (me) working on rare _spare time only_. So, unless someone is ready to fund a proper professional infrastructure, this is unlikely to change, unfortunately.

The current situation for versioning, software and documentation delivery is the following:

- The version number is _major.minor-commit_. A _major.minor_ is [released](https://github.com/tsduck/tsduck/releases) exactly once.
- The _commit_ part is continuously incrementing. A _commit_ usually refers to a given state of the source code repository. In a [released](https://github.com/tsduck/tsduck/releases) version, the _commit_ number is the latest one for this _major.minor_. For instance, the latest released version, as of today, is 3.15-1008. This means that the next commit was 3._16_-1009 (and is not an officially released version). Today, the repository contains 3.16-1068. The official 3.16, when it is released, will have some higher _commit_ number.

- A [released](https://github.com/tsduck/tsduck/releases) binary package contains the documentation and changelog which is consistent with this package (the documentation is installed along with the binaries). This does not mean that the version number which is printed in the documentation has the same _commit_ number. For instance, the official release 3.15-1008 contains a changelog and a user's guide which are both marked as 3.15-1007. This only means that there is nothing between -1007 and -1008 which changes the documentation. In other words, I do not change the documentation just to update a version number.
- The published documentation on the web site is usually the most up-to-date version from the repository. If you read them online, you read the current state of the project. If you install a binary, you install the documentation _for this binary_. Some users install the official binaries, some others prefer to use the latest updates and fixes and prefer to rebuild from the repository. So, there is not one single right choice for which version to publish.

As a conclusion, I use my (long) experience in professional software development and delivery to try to provide the best possible free open-source software within the limitation of zero resource and zero funding.

**Comment by paretech** [comment]
Hi @lelegard 

I understand and that makes sense. The information you provided in the versioning description helps me understand the workflow and to use the artifacts as intended.

Thank you for developing this software and making it available. I am impressed by the software and infrastructure you have developed and deployed. Keep up the great work.
