### ISSUE TITLE
How to add HEVC descriptors and processing?

### ISSUE THREAD

**Issue by alexander-nf** [tsduck/tsduck#19]
I added to:

.\src\libtsduck\tsduck.dvb.names, `[StreamType]`:
`0x24 = HEVC video`

.\src\libtsduck\tsduck.dvb.names, `[DescriptorId]`:
`0x38 = HEVC video`

.\src\libtsduck\tsduck.dvb.names, `[ComponentType]`:
`0x0900 = HEVC Main Profile high definition video, 50 Hz`
`0x0901 = HEVC Main 10 Profile high definition video, 50 Hz`
`0x0902 = HEVC Main Profile high definition video, 60 Hz`
`0x0903 = HEVC Main 10 Profile high definition video, 60 Hz`
`0x0904 = HEVC ultra high definition video`

.\src\libtsduck\tsduck.dvb.names, `[ServiceType]`:
`0x1F = HEVC digital television service`

I got values from [ETSI EN 300 468 1.15.1](http://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.15.01_60/en_300468v011501p.pdf), 6.2.33 'Service descriptor', 'Table 86: Service descriptor'.

But I feel additions I made above are not enough for proper TS processing. And other modifications should be made, like addition to:

.\src\libtsduck\tsMPEG.h:
`ST_HEVC_VIDEO  = 0x24, //!< HEVC video`

.\src\libtsduck\tsMPEG.cpp:
insertion of `ST_HEVC_VIDEO` into checks `IsPES`, `IsVideoST`

**Comment by lelegard** [comment]
Good point again, I will do it.

**Comment by alexander-nf** [comment]
Hi, Thierry!

I've tested TS with HEVC service by `tsp` .. `-P analyze` (TSDuck build 463) and I've got expected description of HEVC elementary stream in a report.

Of course, it's not an extensive test, but I think the enhancement was made. Thanks!

**Comment by lelegard** [comment]
Thanks for the feedback. But you are pulling too fast ! It was not yet completed in build 463. The final build for HEVC signalization support is 466 :)

In XML files, the tag `<HEVC_video_descriptor>` is now recognized as well.

Closing this issue.

Fixed in 548de41520e66aeb3ef99abd63fe2ea2eed598a3
