### ISSUE TITLE
HLS Input

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#193]
A nice feature to help debug would be a --save-segments which woul save the segments as they are received to the current directory or even better a specified directory.

The reason is due to a problem pulling a HLS stream with TSP and then processing this with FFMPEG, PTS and DTS errors, so no video frames are processed.

**Comment by lelegard** [comment]
Why not using `-P file something.ts` between `-I` and `-O` ? It won't save the segments individually but you get the content file.

**Comment by joolzg** [comment]
My idea was to be able to run the tests with HLS offline, hence needing the segments.

**Comment by lelegard** [comment]
Added option `--save-file` which specifies a directory where all downloaded files, playlists and media segments, are saved.

**Comment by joolzg** [comment]
Thanks for that, will aid me in finding out why my filtering code is not working.
