### ISSUE TITLE
HLS input picks lower bitrate than a closer lower one

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#198]
tsp -v -I hls --min-bitrate 528000 "http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8" -O drop

Picks the 18400 but i would expect it to pick the 364000 bitrate.

Would this be the correct idea behind the command?

**Comment by lars18th** [comment]
Hi @joolzg ,

The documentation lists this:
```
--min-bitrate value
When the URL is a master playlist, select a content the bitrate of which is higher than the
specified minimum.
```

So, if not a bitrate _over_ 528K then you get the first one in the list (perhaps the lowest).

So perhaps @lelegard can change the behaviour with one of these two options:
- Option A: If the `--min-bitrate` can't be applied, return with an error.
- Option B: Or select the nearest lower bitrate.

Regards.

**Comment by lelegard** [comment]
Hi,

> Picks the 18400 but i would expect it to pick the 364000 bitrate.

I don't see the same behavior. In my case, it selects a stream with 664000 b/s:
~~~
 tsp -v -I hls --min-bitrate 528000 "http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8" -O drop
* hls: downloaded master.m3u8, master playlist, static, 12 media playlists
* hls: selected playlist: http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/index_664_av-p.m3u8?sd=10&rebase=on, 640x360, 664,000 b/s
~~~

Currently, it is assumed that the streams are ordered in the master playlist in decreasing order of preference (hence, the first one being the default one). When min/max conditions are specified, all streams are examined in sequence and the first one which matches all conditions is selected.

If no matching stream is found, there is an error and `tsp` stops. This is why it is surprising that you get a stream with a lower bitrate than specified. I mean a _declared_ lower bitrate in the master playlist.

**Comment by lelegard** [comment]
Hi @joolzg 

Can you confirm that you get a stream with a _declared_ bitrate which is lower that `--min-bitrate` ?

As I described, this should not be possible and I would like to confirm if there is a problem with that.

**Comment by joolzg** [comment]
Just tried with the command from my 1st post and seems to be picking the 664 bitrate not 184 or 364
