### ISSUE TITLE
Dektec DTA-107S2 parameters ignored?

### ISSUE THREAD

**Issue by rezna11** [tsduck/tsduck#2]
I'm getting very low power (-47dBm) output from DTA-107 modulator. Had the same issue with Dektec's Streamxpress but after installing Dektec SDK, I'm getting full power in Streamxpress but still very weak from TSDuck. Haven't tested another OS, just W2008R2SP1.

**Comment by rezna11** [comment]
The previous issue was fixed by installing Dektec SDK and rebooting PC again. But now I'm getting 100% power on the output and --level parameter has no effect

**Comment by rezna11** [comment]
Looks like the --modulation nor --level parameters work for DTA-107... tsp uses the last values that were previously set by StreamXpress!

**Comment by lelegard** [comment]
Looking at the source code, the two options are actually passed to DTAPI, the Dektec API that drives the device. However, I have not used any DTA-107 for years and I do not have any now. I will ask some colleagues if they have any to test.

**Comment by rezna11** [comment]
After trying in Windows 10 and Windows 2016, it really seems to me that the tsp command line parameters are not set correctly, not only the level and modulation but perhaps other too. FEC and SR seem to work, at least in some cases.

**Comment by lelegard** [comment]
Could you provide a sample command with all parameters? How do you determine that they are not set correctly? Could you post the values you measure if you have a spectrum analyser or equivalent?
Thanks

**Comment by rezna11** [comment]
Sorry, I'm an idiot, I entered "-30" (habit from working with DtPlay) but it should have been "-300", no wonder the modulator was acting strange. During my tests I also didn't encounter the issue with modulation settings, I think it was all caused by wrong level I was entering.

**Comment by lelegard** [comment]
No problem, we all make mistakes sometimes.
Closing this one.
