### ISSUE TITLE
Release v3.16

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#200]
Hi @lelegard ,

I hate to request for ETAs of new releases... But I do all tests with Linux and WSL (very easy to compile). And for the native Windows executable I use the official releases.

So, as the core of the v3.16 release seems to be the HLS support (that's now completed), and the last release has around two months old: You will release soon the v3.16?

Please, remove/close this issue if you're not comfortable with this question (and I'll never ask about it again). :innocent:
Regards.

**Comment by lelegard** [comment]
Version 3.16 will be released when ... it is ready.
I have enough pressure on deadlines in my job, so I enjoy the feedom to avoid them in TSDuck.
At least, the bug in #196  must be fixed first.
And since you allow me to close this issue, I do it.
