### ISSUE TITLE
table_id values collision in tsduck.dvb.name

### ISSUE THREAD

**Issue by alexander-nf** [tsduck/tsduck#21]
I tried to add AITs detection and found table_id collision:

.\src\libtsduck\tsduck.dvb.names, `[TableId]`:
~~`0x74 = Resolution Notification`~~
**`0x79 = Resolution Notification`**

[ETSI TS 102 809](http://www.etsi.org/deliver/etsi_ts/102800_102899/102809/01.03.01_60/ts_102809v010301p.pdf):
**`0x74 = AIT (Application Information Table)`**

Both IDs are also in [ETSI EN 300 468](http://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.15.01_60/en_300468v011501p.pdf), 5.1.3 'Table 2: Allocation of table_id values',

**Comment by lelegard** [comment]
Hi @alexander-nf 

Good spot !
I just fixed it.
