### ISSUE TITLE
Feature suggestion - could tsscan create zap configuration files (Windows)?

### ISSUE THREAD

**Issue by oviano** [tsduck/tsduck#211]
We have the scanning, and we can specify zap files/format as the input when tuning to a channel, which is great but if you are on Windows there is no way I can see for creating the zap files in the first place, other than manually.

Is that something that might be possible one day?

**Comment by oviano** [comment]
Thank you. According to the reference I linked to in the other thread it talks about azap and gives sample output.

But you will know far better than me (a complete newbie!) as to whether that me whole zap thing is obsolete or not.

-Oliver

**Comment by oviano** [comment]
Just to add a few thoughts.

It’s not zap in particular that is necessarily the point - it would just be useful when you are on the Windows platform to be able to run a scan to output all the channels to some file and then be able to tune to those channels easily by referencing their name in the file.

Doesn’t have to be zap necessarily it could be something tsduck-specific.

**Comment by lelegard** [comment]
> Doesn’t have to be zap necessarily it could be something tsduck-specific.

Yes, the "zap" format is definitely obsolete and non extensible. I will define some XML syntax to replace this. The TSDuck will drop support for the "zap" format.

**Comment by oviano** [comment]
Sounds good!

**Comment by lelegard** [comment]
The replacement of the old Linux-specific "zap" format by an XML file has been done. `tsscan` can create or update such files. See the user"s guide for the details.

**Comment by oviano** [comment]
This is brilliant and much appreciated. Thank you!
