### ISSUE TITLE
Utah OTA ATSC Capture samples

### ISSUE THREAD

**Issue by oviano** [tsduck/tsduck#244]
https://www.dropbox.com/sh/45axzxcyx7uod3a/AADhRz_qgmFRM-V58Gj4AzA3a?dl=0

Also includes the channels.xml file from the corresponding scan of the network and capture.bat showing the command used to capture.

There should be 17 transport stream files, each of 60s in duration. At the time of writing it has about one hour remaining to upload them all.

Please let me know when you've moved these to the tsduck repo so I can delete.

Just to add that some of them won't be perfect streams due to reception problems.

**Comment by lelegard** [comment]
Hi Oliver,
Thanks a lot !
I just downloaded them. I will probably publish them in the [streams repository](https://tsduck.io/streams/), if you do not mind.

**Comment by oviano** [comment]
That's fine.
