### ISSUE TITLE
HLS Output Initial segment number

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#253]
When restarting it would be good to be able to specify the start number for the segment, so instead of going back to 0 we could restart from an arbitary point

--start-segment-number X

**Comment by lelegard** [comment]
Hi @joolzg, The option `--start-segment` has been added in version 3.17 as a response to request #197 from ... @joolzg 😉

**Comment by joolzg** [comment]
This is for HLS output, sorry

**Comment by lelegard** [comment]
What do you mean by start segment number in an output playlist?
Is it the value of `#EXT-X-MEDIA-SEQUENCE` ?

**Comment by joolzg** [comment]
Yes, as if a stream stops and restarts it would be nice to carry on with the sequence instead of starting at 0

**Comment by lelegard** [comment]
Option `--start-media-sequence` has been added.

**Comment by joolzg** [comment]
Thanks again
