### ISSUE TITLE
--negate for sifilter

### ISSUE THREAD

**Issue by suvorau** [tsduck/tsduck#254]
Hi @lelegard , thank you so much for this amazing tool!

Is there a way to filter out PMT with unknown PID? `sifilter` looks like a perfect plugin for this but it lacks `--negate` option. 
Is there another way to find PMT which PID is unknown?

Thank you!

**Comment by lelegard** [comment]
> Is there another way to find PMT which PID is unknown?

I do not understand the question. What do you mean by "PMT which PID is unknown" ?

Do you want to display any specific PMT which is not referenced in the PAT ? All of them ?
