### ISSUE TITLE
Encapsulation plugin: SYNC mode

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#272]
Hi @lelegard ,

When the Transport Stream is remuxed including an encapsulated stream, not all external tools can handle the stream without PTS marks. So, I enhanced the PES encapsulation with support of both: Asynchronous (new) and Synchronous (regular) mode.

Please, test my last PR #271. All description and examples are included in the headers.
I hope you agree to merge it.

Regards.

**Comment by lelegard** [comment]
Merged
