### ISSUE TITLE
Help: How to identify a packet and execute an action

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#278]
Hi @lelegard ,

Please, can you help me by explaining how to achieve this goal?

- Inside a PID a need to identify duplicated packets. A duplicated packet is any packet that the next packet in the pid is identical (all bytes are equal), so no differences. And the goal is to change the pid number of the _duplicated_ packet. So, the first continues without changes and the next will change to a new pid.

Any idea how to get it?
Thank you for your time.

**Comment by lars18th** [comment]
Hi @lelegard ,

Another option more generic can be this:
- Provide a "check" plugin that finds if a packet has some values (for example `0x81;0x11;0x00` at given offset) and then it executes an action (in this case change pid). One example:
`-P check-packet -pid 100 --label 0x81;0x11;0x00 --label-offset 35 --change-pid 101`

And the options can be `--change-pid`, `--remove`, `--duplicate`, `--patch` (where "patch" is like "label" and "label-offset" to change content of the packet).

What you think?

**Comment by alaaodeh** [comment]
Hi @lelegard ,@lars18th

Kindly I used the command 

 -P check-packet -pid 100 --label 0x81;0x11;0x00 --label-offset 35 --change-pid 101
but required file and i need the input from DVB s2 signal and drop specific packet

**Comment by lelegard** [comment]
Options `--pattern`, `--search-payload` and `--search-offset` have been added to plugin `filter`. See #296.

**Comment by lars18th** [comment]
OK. I close this issue, and I continue inside #296 .

Thank you!
