### ISSUE TITLE
use frontend1 on TBS 5520SE for dvb-s2 

### ISSUE THREAD

**Issue by samerajarmeh** [tsduck/tsduck#311]
how to read from frontend1
this usb adapter have multistandard tuner (frontend0 for dvbt,dvbc.. and frontend1 for dvbs)
[ 1716.700056] usb 2-1.2: DVB: registering adapter 1 frontend 0 (TurboSight TBS 5520SE DVB-T/T2/C/C2/ISDB-T)...
[ 1716.700159] usb 2-1.2: DVB: registering adapter 1 frontend 1 (TurboSight TBS 5520SE DVB-S/S2/S2X)...
with tsduck only can use dvbc or dvbt
but i need dvbs
its working fine with dvblast

**Comment by rezna11** [comment]
I don't have such tuner but from a quick look at the manual, I would think that using device name /dev/dvb/adapter1:1 should work but it's hard to tell because you didn't even say what commands you tried
