### ISSUE TITLE
TSP: HLS vs VLS - Live Playback

### ISSUE THREAD

**Issue by Sefy76** [tsduck/tsduck#315]
When opening the same URL in both VLC and the TSP/HLS input, i've noticed that HLS is ahead of VLC (which is great) but it gets some buffering in the Live.

Is there anyway to introduce a delay of lets say 30 sec or more, or maybe increase buffers on HLS?

**Comment by lelegard** [comment]
Please read the [TSDuck user's guide](https://tsduck.io/download/docs/tsduck.pdf). The reference section for `tsp` lists the various options which involve buffering. Also read the section about the plugin `hls` and its option `--start-segment`. Testing these various options may give you a clue.

**Comment by Sefy76** [comment]
Thanks, i'll take a look at that!
