### ISSUE TITLE
Looking for frequency

### ISSUE THREAD

**Issue by LordValdrick** [tsduck/tsduck#32]
I'm looking for frequency parameter inside a transport stream, but I could not find anything.

**Comment by lelegard** [comment]
I am not sure to understand what you are looking for.

In the NIT, you will find delivery descriptors which should contain frequencies and modulation parameters. But this depends on the good will of the operator and/or broadcaster. 

Tools like tstables or tspsi or equivalent plugins will display the content of the NIT.

**Comment by LordValdrick** [comment]
Thank you very much, this is very helpful.
Also, your open source is awesome.
