### ISSUE TITLE
question: --terminate equivalent using -P merge

### ISSUE THREAD

**Issue by felipewd** [tsduck/tsduck#328]
Hi,

This is an awesome project! I'm throughly enjoying testing it with our scenario.

Using `mux` plugin I can use `--terminate` to indicate the packet processing should terminate after the input ends.

Is there any way to achieve this using `merge`? 

I'm trying to merge a 10min-TS file in a multicast live stream...but would like tsp to quit after the input file ends. Can this be achieved?

Thanks!

**Comment by felipewd** [comment]
One option would be to use `-P until --seconds <time of the input>`  after `merge` before `-O`...but I'm hoping there's a more elegant solution :-)

**Comment by lelegard** [comment]
`merge --terminate` will be added.

**Comment by lelegard** [comment]
Added options `--terminate` and `--joint-termination` to plugin `merge` in commit 6176bee272c4fd9d155fd958109bce722d3dfd87

**Comment by felipewd** [comment]
Works great, thanks!
