### ISSUE TITLE
BISS 2 mode CA EMM - table_id is listed wrong (cosmetic)

### ISSUE THREAD

**Issue by nautilus7** [tsduck/tsduck#336]
Hi, in most crypto systems, ECMs have table_id 0x80 or 0x81. In BISS2 mode CA, only possible table_id for the ECM is 0x80, while table_id 0x81 and up are used for the EMMs.

You can find the spec here (page 16): https://tech.ebu.ch/docs/tech/tech3292s1.pdf

As a result, when running tsanalyze for a biss2 mode CA sample, the listing is wrong:

```
===============================================================================
|  TABLES & SECTIONS ANALYSIS REPORT                                          |
|=============================================================================|

.
.
.

|=============================================================================|
|  PID: 0x0020 (32)                          European Broadcasting Union ECM  |
|  Service: 0x0001 (1) TESTCA                                                 |
|-----------------------------------------------------------------------------|
|  0x80 (128, ECM (even)), TID ext: 0x0004 (4)                                |
|      Repetition: ...... 58  ms  Section cnt: ...... 970  First version  19  |
|      Min repet.: ....... 3  ms  Table cnt: ........ 970  Last version:  23  |
|      Max repet.: ..... 118  ms  Versions: ............. 19, 20, 21, 22, 23  |
|=============================================================================|
|  PID: 0x0021 (33)                          European Broadcasting Union EMM  |
|-----------------------------------------------------------------------------|
|  0x81 (129, ECM (odd)), TID ext: 0x0004 (4)                                 |
|      Repetition: ...... 42  ms  Section cnt: .... 1,338                     |
|      Min repet.: ...... 21  ms  Table cnt: ...... 1,338                     |
|      Max repet.: ...... 94  ms  Version: ............ 1                     |
|=============================================================================|
```

A similar problem exists with tstables as well, and maybe with other modules. CAT clearly states that pid 0x0021 is the EMM pid, but right below, pid 0x0021 is listed as ECM (odd).

```
* CAT, TID 1 (0x01), PID 1 (0x0001)
  Version: 1, sections: 1, total size: 24 bytes
  - Section 0:
    - Descriptor 0: CA (0x09, 9), 10 bytes
      CA System Id: 0x2610 (European Broadcasting Union), EMM PID: 33 (0x0021)
      Private CA data:
      0000:  80 04 00 04 00 EB                          ......

* ECM (odd), TID 129 (0x81), PID 33 (0x0021)
  Version: 1, sections: 1, total size: 282 bytes
  - Section 0:
    TIDext: 4 (0x0004)
    0000:  00 EB 81 0F F0 00 98 2B 94 D4 EB B0 35 67 54 4C  .......+....5gTL
    0010:  94 8A 3E 64 A5 38 5F B5 62 D7 92 04 3B 56 A8 17  ..>d.8_.b...;V..
    0020:  09 6F 13 93 8F 67 04 E3 64 F0 04 79 E7 09 6F 7E  .o...g..d..y..o~
    0030:  91 45 57 F7 75 B9 6A BB F5 AA 18 D6 DA 00 AB E9  .EW.u.j.........
    0040:  FA AE A9 1D AF 57 F1 33 9C A2 03 03 16 1F 31 BA  .....W.3......1.
    0050:  8A FB BB 17 98 62 F1 F5 02 E8 84 30 9F 8B 7B BF  .....b.....0..{.
    0060:  62 93 64 B9 29 A9 F0 5D D3 C8 B2 E7 48 CD 49 9C  b.d.)..]....H.I.
    0070:  AB 07 81 0C 34 51 D6 FD 7C 04 93 7C 60 9F AA 1A  ....4Q..|..|`...
    0080:  FE 02 03 2A 3A D9 09 15 E0 9E 61 C5 9E 76 44 A3  ...*:.....a..vD.
    0090:  ED 91 E8 4E AB E9 4B 03 A2 85 6C 14 E9 4A 57 21  ...N..K...l..JW!
    00A0:  8F 30 F3 8A F2 1E 07 A5 91 1D 10 AD 34 58 37 9A  .0..........4X7.
    00B0:  F1 43 0C 5B D6 CE 3A FC 10 33 8F 98 8A 7B 57 70  .C.[..:..3...{Wp
    00C0:  C7 F1 2B AF 29 5B 7F 8B C0 EB 0C 03 6A 98 7A 70  ..+.)[......j.zp
    00D0:  E9 50 3C 9C 37 78 94 63 E7 ED 37 86 61 7A 9E 2D  .P<.7x.c..7.az.-
    00E0:  81 E8 EC E3 59 5F 41 90 FD E3 01 9D 77 55 BF 14  ....Y_A.....wU..
    00F0:  BE CE 38 1A 00 BF CA 8C C7 DA AA 47 DF 44 8E F0  ..8........G.D..
    0100:  9A 25 1D 85 8A 4C 53 19 9C EC 7C E1 7B 05        .%...LS...|.{.
```

**Comment by lelegard** [comment]
OK, this is specific to this CAS. I haven't read the full spec, so I do not know how they alternate session words and renew ECM's. In most other CAS, the table ids 0x80 and 0x81 and used to facilitate the section filtering and get notified only once per crypto-period.

Anyway, according to the spec intro, this system is designed to protect contribution feeds, not individual subscribers. So, it is very specific.

**Comment by nautilus7** [comment]
Like BISS1, BISS2 will be used for feeds between providers.
Yes, in other CAS, table_ids 0x080 and 0x81 are used interchangeably, but not in BISS2.

The ECM and EMM tables in BISS2 follow the syntax of the private section as defined in paragraph 2.4.4.10 of Rec. ITU-T H.222.0. This is also stated in the pdf I linked in my first post. There is a "version_number" inside every "private section" and thus in every ECM.

tsanalyze detects ECMs with "version_number" 19, 20, 21, 22, 23 (for my sample), so I guess, this is how they "renew" ECMs.

For alternating between odd and even session words (or control words), they use the "transport_scrambling_control" of the each TS packet.

**Comment by lelegard** [comment]
OK, their ECM and EMM use the long-section / multi-section syntax while most (all?) other CAS use short-section / mono-section syntax. In that case, the version number is used to trigger a new ECM. Because they conform to the long-section usage rules, TSDuck will get each ECM exactly once. So, this is fine (except the name).

This is strange that they made that choice. On an MPEG/DVB perspective, the versioned long-syntax should be used for cycled tables with a long life-time (e.g. PAT, PMT, NIT, etc) while the short-syntax should be used for small rapidly modified (or even one-shot) sections (e.g. ECM, EMM, TOT, TDT).

That being said, I have seen worse in ATSC where long-syntax tables are changed without changing the version number, which is not even MPEG-compliant...

Anyway, a CAS which publicly publishes the syntax of its ECM's and EMM's must be a joke 😉

**Comment by rezna11** [comment]
I think BISS was not meant to be super secure, it’s free and included in
many scramblers and IRDs without extra licenses. It’s only used to make
copyright owners happy. Of course Sky or C+ would never use BISS.

**Comment by nautilus7** [comment]
@lelegard BISS2 doesn't seem a joke. Its EMMs are encrypted using asymmetrical encryption (RSA 2048 OAEP). Also the actual audio and video packets are scrambled with DVB-CISSA (AES128 CBC), so they are much more immune to rainbow attacks, unlike CSA. No other CAS does any of these, AFAIK.

@rezna11 we are talking about BISS2 here, which is a step further in security with rolling 128bit control words, while BISS1 uses a constant 48bit control word.

**Comment by onajafi** [comment]
@nautilus7 Can you share your BISS-CA scrambled samples? I've tried to search everywhere but didn't find any .ts file to have such a thing.

**Comment by nautilus7** [comment]
https://limewire.com/d/DfWvk#wec1yVrs8X
