### ISSUE TITLE
ecm message

### ISSUE THREAD

**Issue by michaeladams123** [tsduck/tsduck#341]
hi,
i have issue with some ecm when received to stb  ecm contain message to stb to show messages like hashcode watermark on TV and i need to filter or block it please i need your kindly support.

**Comment by lelegard** [comment]
Is this a joke ?

Are you asking how to circumvent a security mechanism ? To me ? Please learn to use LinkedIn.

TSDuck is a toolbox for digital TV engineers to do test, monitoring, integration, debug, lab or demo. It has never meant to be used to implement security hacking practices. I cannot prevent anyone to use it outside a legal framework but you should at least have the decency to avoid publicly asking such a question.

You will __never__ get help from TSDuck to hack TV systems.

**Comment by michaeladams123** [comment]
so sorry for that,sure not for hacking just we need to remove ads messages on stb like popup 
so sorry again

**Comment by rezna11** [comment]
Pupup ads in ECMs? Weird. I would think you want to remove the serial from being shown on screen which is part of CAS. I've seen that stuff in India in hotels... all channels had a number appear on screen every couple of minutes, always in different place. So I would guess you want to remove it so that you can encode the channel for illegal IPTV streaming.

**Comment by lelegard** [comment]
ECM’s are designed to transport information which is essential to the security of the system and pure commercial ads are not part of this. 

Users discussing security hacking will be banned from this forum.

**Comment by michaeladams123** [comment]
sorry , we have legal IPTV and telecommunication company, and we are used your very power full tool to monitor the stream,and just we need to remove the hashcode because the provider can't customize it for one customer

**Comment by michaeladams123** [comment]
sure no security hacking and so sorry for misunderstand
