### ISSUE TITLE
ts file inject

### ISSUE THREAD

**Issue by michaeladams123** [tsduck/tsduck#342]
hi,

please i need your kindly support to inject xml ecm and i need to inject it to udp stream every 100 ms.

Regards

**Comment by michaeladams123** [comment]
-P inject nit-sanshs.xml --pid 3588 --replace --stuffing  -O dektec --device 0 
this command correct and i need to replace the file as a loop forever

**Comment by lelegard** [comment]
ECM's are dynamic tables which are generated by an ECMG and inserted by the plugin `scrambler`. Inserting static ECM's from an XML file is pointless at best, serving illegal operation at worst. Considering other suspect requests about messing with ECM's from the same author, this request is closed.
