### ISSUE TITLE
st2022-7 support

### ISSUE THREAD

**Issue by gmadeo** [tsduck/tsduck#366]
This is a feature request.

I am using tsswitch fast switching to receive a redundant service via 2 paths. I have the ability to align the streams via the 2 paths to match their latency so the switching is very quick. It works really well, but the switching is not seamless, as expected.

There is a SMPTE spec, st2022-7 for Seamless Protection Switching of RTP Datagrams. It is essentially a buffer reconstructed from the two RTP streams.

It would be great if support for this could be added to tsduck.

Thanks for your awesome work!

**Comment by lelegard** [comment]
This is typically a application for production systems. Out of the scope of TSDuck.
