### ISSUE TITLE
Plugin rmsplice on DVB-C

### ISSUE THREAD

**Issue by gmarsico** [tsduck/tsduck#376]
Hi all

I'm doing some tests trying to remove the ads on a TS with SCTE-35.
The original stream have two programs, according to the manual rmsplice needs to be executed in a SPTS, so I use the zap plugin to get a file with only one program. After that I tried to execute the rmsplice, but the SPTS file and the result of rmsplice are exactly the same.
I noticed that the tests were made with T2-MI streams, does rmsplice works also on streams without T2-MI?
The original stream shows on the service that it's intended to be rmspliced:

```
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Digital television service ................... C    4,414,650 b/s  |
|  0x0FAA  MPEG-2 Video (720x480i, @24 Hz, 4:3, 4:2:0) .. C    4,117,696 b/s  |
|  0x0FB1  SCTE 35 Splice Info .......................... C            1 b/s  |
|  0x0FB7  ATSC AC-3 Audio (eng, AC-3, stereo (L,R), @48  C      141,012 b/s  |
|  0x0FB8  ATSC AC-3 Audio (spa, AC-3, stereo (L,R), @48  C      141,012 b/s  |
|  0x1403  PMT .......................................... C       14,927 b/s  |
|          (C=Clear, S=Scrambled, +=Shared)                                   |
```
And the pid:

```
|=============================================================================|
|  PID: 0x0FB1 (4017)                                    SCTE 35 Splice Info  |
|  Service: 0x007B (123) CTN PNR HD AC3                                       |
|-----------------------------------------------------------------------------|
|  Single Service PID        Transport:                Discontinuities:       |
|  Bitrate: ......... 1 b/s  Packets: ............. 6  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|                            Duplicated: .......... 0  Sections:              |
|                            PCR: ................. 0  Unit start: ....... 6  |
```

If it's needed I can upload the ts file to be reviewed.

Thanks

Gustavo

**Comment by lelegard** [comment]
> I noticed that the tests were made with T2-MI streams, does rmsplice works also on streams without T2-MI?

The tests are made on an original Russian T2-MI decapsulated stream because this was the first "real world" stream I got with real production SCTE-35 cues. But the magic of `tsp` is that any plugin can work on any input stream. A stream is just a stream. CVB-C, T2-MI or IPTV are all equal.
