### ISSUE TITLE
Option not in DVB

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#403]
I would like to be able to do the same as --satellite-frequency but on a dvb input.

Reason for this is an exotic LNB which seems to not behave and the only way i have it working with dvblast is using the IF frequency.

If its possible without this command can you give me a hint

Also tried this from the tsduck.pdf
tsp -I dvb --tune 11856:v:0:27500 -P until -seconds 20 -O file ts_capture.mpg
tsp: dvb: unknown option --tune
tsp: dvb: no parameter allowed, use options only
tsp: until: invalid integer value econds for option --seconds (-s)
tsp: until: no parameter allowed, use options only

**Comment by lelegard** [comment]
Hi @joolzg,

With `-I dvb`, the `--frequency` option is already a satellite frequency. The intermediate frequency, at the input of the tuner,  is computed from the LNB characteristics. If you have a non-standard LNB, then specify its frequency characteristics using option `--lnb`.

With `-O dektec`, the `--frequency` option is the output frequency of the modulator. The option `--satellite-frequency` is a way of computing  `--frequency` as if it was a downlink and there were a reception LNB. This is easier to reproduce the frequency of an actual satellite transponder.

I agree that the intermediate frequency and the satellite frequency are not consistent but, for the sake of simplicity, the option `--frequency` is mapped to the most frequent use case for the corresponding plugin.

**Comment by joolzg** [comment]
OK
