### ISSUE TITLE
IDEA: NULL stuff for HLS input

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#435]
Hi @lelegard ,

I'm triying to transform some HLS stream (in fact, I'm testing with `https://mcdn.daserste.de/daserste/de/master.m3u8`) to craete a suitable full MPEG-TS compatible with DVB-T. However, as the HLS input doesn't have NULL stuff, it's impossible to add missing tables.

So, please can you add some option in the HLS input plugin to add NULL stuff?

Thank you!

**Comment by lars18th** [comment]
I missed to comment the option... I suggest to use the same as for the global tsp `-a nullpkt/inpkt
--add-input-stuffing nullpkt/inpkt`. 

So you can use:
`tsp -I HSL --add-input-stuffing 1/10 https://mcdn.daserste.de/daserste/de/master.m3u8 ... `
to add 1 NULL packet every 10 readed.

I hope you agree.
Regards.

**Comment by lelegard** [comment]
This is exactly what the option `--add-input-stuffing` is already doing. Did you try it?

**Comment by lars18th** [comment]
> This is exactly what the option `--add-input-stuffing` is already doing. Did you try it?

Oppss! I discovered now... I think it only works with other inputs.

Thank you!
