### ISSUE TITLE
tsp ip SMM - Warning on SMM address

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#443]
tsp: TSDuck - The MPEG Transport Stream Toolkit - version 3.18-1361

```
tsp.exe -I ip 2 10.216.154.254@237.2.6.65:5500 -P continuity -O drop
* Warning: ip: address 237.2.6.65:5500 is not an SSM address
```

**Comment by lelegard** [comment]
Hi @enricovittorini,

What is your question?

If you'd like an explanation on the message, just have a look at the [Wikipedia article on SSM](https://en.wikipedia.org/wiki/Source-specific_multicast) (not SMM). It says that source-specific multicast (SSM) addresses should be in the range 232.0.0.0/8. Your address 237.2.6.65 is consequently not an SSM address, hence the warning message. That being said, it should work anyway. It just warns you that you possibly typed the wrong address.
