### ISSUE TITLE
SVRENAME plugin: work with unkown service in SPTS

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#450]
Hi @lelegard ,

The current implementation of the `svrename` plugin requires the specificacion of the target _service_ (sid or name). However, in some cases when the input is a SPTS the sid number is unkown. In fact, with just one service this parameter is irrelevant.

So, I request to add support for `-P svrename -i 1 *` or `-P svrename -i 1 -1`. In this case `*` or `-1` will indicate to use _any_ sid number inside the TS.

You think this has sense?

**Comment by lelegard** [comment]
Good idea

**Comment by lelegard** [comment]
Done. The service name or id is now simply optional. When omitted, the first (or only) service in the PAT is used.
