### ISSUE TITLE
tstables --nagate-pid

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#458]
```
tstables --version
tstables: TSDuck - The MPEG Transport Stream Toolkit - version 3.18-1361
```

How to negate a PID
```
tsp -I ip -l 192.168.111.1 192.168.111.134@239.0.0.1:5500 | tstables --negate-pid 20
* Warning: ip: address 239.0.0.1:5500 is not an SSM address
tstables: cannot open file 20
```

**Comment by lelegard** [comment]
Well, the answer is RTFM as usual...

The option `--negate-pid` does not take any value and excludes all PID's which are specified by all `--pid` options. So, the right command would be:
~~~
tstables --pid 20 --negate-pid
~~~

In your case, you would rather use the plugin `tables`:
~~~
tsp -I ip ... -P tables --pid 20 --negate-pid -O drop
~~~

The command `tstables` is just a convenient shortcut for:
~~~
tsp -I file _filename_ -P tables ... -O drop
~~~
