### ISSUE TITLE
Unable to rename ServiceID from TS file. System error 193 (0x000000C1)

### ISSUE THREAD

**Issue by kmteam** [tsduck/tsduck#476]
I'm getting the following error when I try to rename a ServiceID from a TS file using tsduck on a Windows 10 host.
```
C:\tmp\foo>tsp -I MY_TS_FILE.ts -P svrename 0x00BA --id 0x01
tsp: MY_TS_FILE.ts: System error 193 (0x000000C1)
```
I'm running a fresh installation of TSDuck

> tsp: TSDuck - The MPEG Transport Stream Toolkit - version 3.19-1520

Any idea? 
Thnks!

**Comment by lelegard** [comment]
Please RTFM. The correct syntax for your case is:
~~~
tsp -I file MY_TS_FILE.ts -P svrename 0x00BA --id 0x01
~~~
There are many input plugins. The one that reads files is named `file`. Others are named `ip`, `dvb`, `hls`, etc.

By writing `-I MY_TS_FILE.ts`, the file `MY_TS_FILE.ts` is interpreted as a plugin name. Not finding a plugin with that name, `tsp` ends up with activating this file as a DLL, which eventually gives the system error you see.

Also, you did not mention any output plugin (`-O ....`). By default, the transformed stream is sent to the standard output, which is probably not what you want to do, unless you pipe that command into another one.

`tsp` is a very versatile command. Before using it, be sure to read its description in the user's guide.
