### ISSUE TITLE
Request: Split HLS output based on labels

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#492]
Hi @lelegard ,

This _new_ issue is partially based on #483 , but it takes another direction. So I hope you agree to comment about it:

- The request is about a new parameter for the HLS output plugin: `-f|--flag-cut`. The objective is to split the HLS chunks based on a flag, and not based on duration (`-d`) or size (`-f`). However, these parameters can overlap and then they can be the max. So if the flag doesn't appear for the fixed duration or size, then a nuw chunk is started.

The objective with this new parameter is to contol the HLS chunks for starting them at the GOP boundaries. And how to acomplish this?

- The idea is to use the SPLICE_COUNTDOWN in the Optional Fields of the TS Header. This can be done with the plugin `filter` with a _new_ parameter `--splice-countdown [value]`. This will detect when the countdown value is present with a value of -1 or 0 (or anyother value that the user wants to check it).

For sure it will be the responsability of an external tool to set this value inside the TS Header. However, I feel it will be easy to do it for any compressor/video-processor. And the TSDuck then will maintain the simplicity of a TS processor.

So, I feel this is the most simple and _KISS_ based solution to generate HLS chunks aligned with GOP structures.

What you think?
Regards.

**Comment by lelegard** [comment]
Added options `--has-splice-countdown`, `--splice-countdown`, `--min-splice-countdown` and `--max-splice-countdown` to plugin `filter`.

Added option `--label-close` to output plugin `hls`.
