### ISSUE TITLE
Not building with gcc 8.3.0

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#496]
➜  tsduck git:(master) git pull
Already up-to-date.
➜  tsduck git:(master) gcc --version
gcc (Ubuntu 8.3.0-16ubuntu3~16.04) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  tsduck git:(master) make         
  [CXX] dtv/descriptors/tsAACDescriptor.cpp
In file included from /home/encoder/iptvCode/tsduck/src/libtsduck/base/tsGuard.h:37,
                 from /home/encoder/iptvCode/tsduck/src/libtsduck/base/tsSafePtr.h:38,
                 from /home/encoder/iptvCode/tsduck/src/libtsduck/base/tsByteBlock.h:37,
                 from /home/encoder/iptvCode/tsduck/src/libtsduck/dtv/tsDuckContext.h:37,
                 from /home/encoder/iptvCode/tsduck/src/libtsduck/dtv/tsAbstractSignalization.h:37,
                 from dtv/descriptors/tsAbstractDescriptor.h:36,
                 from dtv/descriptors/tsAACDescriptor.h:36,
                 from dtv/descriptors/tsAACDescriptor.cpp:34:
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:109:5: error: expected ‘;’ after class definition
     }                                                             \
     ^
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:125:5: note: in expansion of macro ‘TS_DECLARE_EXCEPTION’
     TS_DECLARE_EXCEPTION(InvalidValue);
     ^~~~~~~~~~~~~~~~~~~~
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:125:39: error: extra ‘;’ [-Werror=pedantic]
     TS_DECLARE_EXCEPTION(InvalidValue);
                                       ^
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:109:5: error: expected ‘;’ after class definition
     }                                                             \
     ^
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:130:5: note: in expansion of macro ‘TS_DECLARE_EXCEPTION’
     TS_DECLARE_EXCEPTION(UninitializedVariable);
     ^~~~~~~~~~~~~~~~~~~~
/home/encoder/iptvCode/tsduck/src/libtsduck/base/tsException.h:130:48: error: extra ‘;’ [-Werror=pedantic]
     TS_DECLARE_EXCEPTION(UninitializedVariable);

**Comment by lelegard** [comment]
Fixed, sorry for the inconvenience.

**Comment by joolzg** [comment]
Thanks
