### ISSUE TITLE
Playing back HLS with "-P pcrbitrate -P regulate" does not work

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#501]
Testing some HLS streams and it seems that the playback gives burst data, not a nice stready stream.

Are there any factors I should take into account.

**Comment by lelegard** [comment]
If you regulate on PCR's, the PCR's must be correct and the bitrate must be relatively stable. If you have VBR with high instant variations, then you may have problems. The plugin `pcrextract` can extract values which can be ingested in Excel for instance. You may then perform all sorts of analyses.

**Comment by joolzg** [comment]
OK thanks
