### ISSUE TITLE
Latest version giving lots of extra debug

### ISSUE THREAD

**Issue by joolzg** [tsduck/tsduck#502]
Updated to latest git and suddenly im getting these messages
* Error: hls: unsupported HLS tag: EXT-X-CUE-OUT-CONT
* Error: hls: unsupported HLS tag: EXT-X-CUE-OUT-CONT
* Error: hls: unsupported HLS tag: EXT-X-CUE-OUT-CONT
* Error: hls: unsupported HLS tag: EXT-X-CUE-OUT-CONT
* Error: hls: unsupported HLS tag: EXT-OATCLS-SCTE35

Any way of turning them off as they are polluting the log.

**Comment by lelegard** [comment]
The HLS plugin did not change. Your input must have changed.

I will downgrade those messages to debug level. You are right, they do not bring any valuable information outside debugging.

**Comment by joolzg** [comment]
Thanks
