### ISSUE TITLE
No HEVC in ts::PESPlugin::handlePESPacket().

### ISSUE THREAD

**Issue by Avetri** [tsduck/tsduck#555]
https://github.com/tsduck/tsduck/blob/985dd76139b29d763fac6f0ff0a2bc94fd0c52d7/src/tsplugins/tsplugin_pes.cpp#L414

Hi!

ts::PESPlugin::handlePESPacket() doesn't know about HEVC payload and generates warnings. So a checking like pkt.isHEVC() shoud be added to the statement.

**Comment by lelegard** [comment]
Please try commit a4b45865de24060d035275419d16ddb4582d70cf (simply pull the master branch).

The HEVC stream is recognized only from the stream type in the PMT. I hope this will cover your use case.

**Comment by Avetri** [comment]
Thanks.
