### ISSUE TITLE
Cant get past error.. Dont know what I am doing wrong

### ISSUE THREAD

**Issue by RcJetPilotFL** [tsduck/tsduck#564]
Error: inject: input bitrate unknown or too low, specify --inter-packet
* Error: mpeinject: error receiving from UDP socket: Bad file descriptor

Here is command line

tsp -I ip -l 10.7.6.5 6000 \
-P svremove 1 --stuffing \
-P pat --add-service 700/5000 --add-service 701/5002 \
-P inject pmt-int.xml --pid 5000 --bitrate 15000 \
-P inject int.xml --pid 5001 --bitrate 15000 \
-P inject pmt-mpe.xml --pid 5002 --bitrate 15000 \
-P sdt --service-id 700 --name "Demo INT" --provider "TSDuck" --type 0x0C \
-P sdt --service-id 701 --name "Demo MPE" --provider "TSDuck" --type 0x0C \
-P mpeinject -l 10.7.6.5 232.1.1.2:4000  --max-queue 512 --pid 5003 \
 -O ip 10.1.1.1:6000

**Comment by lelegard** [comment]
Answered offline.
