### ISSUE TITLE
Getting all SCTE35 cue messages from TS file 1,5 hour length

### ISSUE THREAD

**Issue by kirill1973** [tsduck/tsduck#569]
Hi,
Can I have all SCTE-35 cue messages from TS file using tsduck in XML format (or another) similar using it for the SCTE-35 injection? Please help me with correct command options/parameters.

**Comment by lelegard** [comment]
Hi,

The command is:
~~~
tstables input.ts --pid NNN --xml cue.xml 
~~~
With `NNN` being the PID number carrying SCTE-35 cues. You can use options `--binary` or `--text` for other output formats.

And as a general guideline, RTFM as usual.

**Comment by kirill1973** [comment]
Thank you very much!
