### ISSUE TITLE
Windows portable binaries missing

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#60]
Hi,

After last commit a new release of Windows binaries is added: the _portable_ version.

However, the files like `TSDuck-Win32-3.12-745-Portable.zip` are still missing in the release section of the github.

Please, upload/update the files.
Thank you!

**Comment by lelegard** [comment]
Wow ! You are going too fast !

This is just the last commit, as you noticed, dating back from last night only. That means that the build procedure now creates the portable packages in addition to the system installers. The portable packages will be available with the next release 3.12-_something_.

**Comment by lars18th** [comment]
:laughing: 
The reason is for testing these _PORTABLE_ binaries in Windows. :wink:

**Comment by lars18th** [comment]
Hi @lelegard ,

I know very well what means _portable_... I'm an intensive user of PortableApps. :smile: 

However, if the binaries are the same, then I only need to extract de EXE files from the installer.

Thank you! :ok_hand:
