### ISSUE TITLE
"eitmerge" plugin

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#62]
Hi,

With the objective of a "simple" and "powerful" future `eitmerge` plugin (proposed in #59), I suggest some ideas about the functionality of this plugin:

- Without specific parameters, the plugin only bypass the EIT info. So it doesn't touch the pid 0x12.
- `--secondary-pid 0x????`: Identifies the EIT info of the merged stream (you called it "merge-pid").
- `--pass-scheduled-others`: It maintains EIT scheduled info of programs in other streams.
- `--pass-scheduled-actual`: It maintains EIT scheduled info of programs in this stream.
- `--merge-scheduled-actual`: It merges (actual) EIT scheduled info from the secondary EIT pid with scheduled info of this mux (uses info from "merge-sid", "merge-all" and "merge-all-exclude").
- `--merge-scheduled-others`: It joins (others) EIT scheduled info of programs from the secondary EIT pid  _without any check_ as other info.
- `--pass-pf-others`: idem for EIT present/forward info.
- `--pass-pf-actual`: idem
- `--merge-pf-actual`: idem
- `--merge-pf-others`: idem
- `--replace-sid ????=????`: Use the EIT info of the left SID (source) as the EIT info for the right SID (target). If some EIT info for right SID exists, then _discard_ it (so use only EIT from source).
- `--merge-sid ????=????`: Idem for the ETI info from the secondary EIT pid. This is used when doing the join action. The source SID is from the secondary EIT pid, and the target is for the current stream.
- `--merge-all`: It accepts all SIDs from the secondary EIT pid. It doesn't do checks about identical SIDs.
- `--merge-all-exclude ???,???,...`: Idem with an exception list of SIDs.
- `--remove-sid ????`: It removes any EIT info of this specific program in any EIT table.
- `--remove-missing`: It removes actual EIT info of programs not found in this stream.
- `--remove-all`: It cleans the EIT info; that's it removes all info.

As you can imagine, the processing logic is relatively simple to implement. All actions are atomic "remove" or "rewrite" triggers. And each action is done when a new EIT packet comes from any of the two sources (without "--merge-pid" the plugin is a simple ETI processor).

Sorry @lelegard if this issue feels you pressurising! That's not my intention. I only like to contribute with a constructive discussion. I hope you accept it! :smile: 

What you think ?

**Comment by lelegard** [comment]
Ideas and suggestions are always accepted, especially when they include some initial analysis.

Thank you for the contribution. Let's keep this issue open for further reference.

**Comment by lars18th** [comment]
> Ideas and suggestions are always accepted, especially when they include some initial analysis.
Thank you for the contribution. 

You're welcome!
If you agree, I'll try too to write some user-case example.

**Comment by lars18th** [comment]
Hi @lelegard ,

Regarding the EIT processing when muxing (`merge`) I have these suggestions after some time working in it:

- The current implementation of TSDuck has already the option for renaming one program from a MPTS and obtain a SPTS with correct EIT info. So, only simple tasks for manipulating the EIT table are required to complete the muxing of the EIT.
- EIT processing: I suggest to include in the `eit` plugin some commands for "processing". Like `--remove-pf-others`, `--remove-pf-actual`, `--remove-orphan` and so on. Also, include and option `--pid` to apply it to a non-standard EIT pid.
- EIT mix: The only remaining task is to "sum", "mix" or "append" multiple pids with EIT into one. So, with `-P eit --merge 180 --merge 280` you can append pids 180 and 280 to the current EIT pid (0x12).
- The idea with the "mix" is to not touch the info data, but complete a mere join. And the idea with the "processing" is do all manipulations (by hand) to obtain correct data (filtering unwanted data and renaming the rest).

I feel this is the most simple approach. Futhermore, you can maintain the current `eti` plugin name. The "-o" will provide additional functionality for extracting info; or you can create a new one `etiprocess`.

However I leave in your hands to define the best implementation.
I hope you agree and soon have some initial implementation.
Regards.

**Comment by lars18th** [comment]
Hi @lelegard ,

I agree with the idea of priorize any task that can't be done outside TSDuck. And this task is an exemple.

So, you agree with implement the remaining "join": `-P eit --merge 112 --merge 212`?
Plus the "pid rename", with a generic `-P filter --rename 12,112` inside the inner tsp of the merge? (I feel that a generic pid-rename will be useful for other tasks too).

Take note that in order to mix the EIT from a `merge`, at time only remains these two tasks for the _basic_ functionality.

I hope you agree.

**Comment by lelegard** [comment]
What is this `-P filter --rename 12,112` ? 
Isn't it the same as `-P remap 12=112` ?

**Comment by lars18th** [comment]
> What is this -P filter --rename 12,112 ?
> Isn't it the same as -P remap 12=112 ?

Yes! :+1: 

I'm still reading the documentation... it's very large. :smile:

**Comment by lars18th** [comment]
Hi @lelegard ,

I update this issue to remind that only a _simple_ functionality is missing (almost for initial support):

- The unconditional EIT join from listed pids to the regular EIT pid 0x12 (**without any check!**).

This can be done inside the `eit` plugin (for example with `-P eit --join 0x112,0x212`), or inside the `merge` plugin (for example with `-P merge --join-eit 0x112,0x212`). Personally I prefer in the `eit` plugin.

What you think?

**Comment by lelegard** [comment]
Hi @lars18th,

I propose something more general. What you need here is to merge sections from several PID's into one single PID, replacing all input PID's by the output PID. Nothing is EIT-specific here. So, a new generic section merging plugin could be used. Quite simple to implement in fact.

In your use case: `-P sectmerge --input 0x12 --input 0x112 --input 0x212 --output 0x12`

**Comment by lelegard** [comment]
Hi @lars18th,

Even more general, I just added the plugin named `sections` which demuxes sections from various input PID's, apply some filtering based on table id or table id extension, and remuxes the remaining sections into an output PID. Very simple to implement, all basic blocks were already there.

To merge your EIT's: `-P sections --pid 0x12 --pid 0x112 --pid 0x212 --output-pid 0x12`

In fact, the default output PID is the first input PID. So, you don't need to mention it here.

To implement things like "remove EIT p/f other", add option `--tid-remove 0x4F`.

You need to pull and rebuild to test it.

**Comment by lelegard** [comment]
Hi @lars18th 

Do we need anything else to merge EIT's ? Without specific `eitmerge` plugin eventually.
I let you close this issue if you consider the topic as completed.

**Comment by rezna11** [comment]
Works fine for merging EPG from multiple streams. Verified in VLC only so far:
![epg](https://user-images.githubusercontent.com/20435164/44785457-41f54200-ab91-11e8-8240-8ab785815fe9.PNG)

**Comment by lelegard** [comment]
Version 3.14 is out, including the `sections` plugin. Closing this issue.
