### ISSUE TITLE
[Q] Cascade change of TransportStream ID and/or NetworkID

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#673]
Hi @lelegard ,

I want to replace _only_ and on-the-fly the TransportStream ID and/or NetworkID of a full MPTS. Instead of manipulating the PAT, NIT, SDT and EIT tables, I want to know if the TSDuck has some command to do it in one place.

Thank you.

**Comment by lelegard** [comment]
Did you try the plugin `tsrename` ?

**Comment by lars18th** [comment]
> Did you try the plugin `tsrename` ?

My memory fails time to time. :laughing:
