### ISSUE TITLE
Default Region for ATSC

### ISSUE THREAD

**Issue by SS-FF** [tsduck/tsduck#689]
Wouldn't it make sense to set the default region to "US" in case of ATSC tuning?

Of course, there is a very small number of additional regions where ATSC is used, but one thing is for sure: the regular default region is "Europe", and that's in no case an appropriate choice for VHF and UHF band configuration when ATSC tuning is requested.

**Comment by SS-FF** [comment]
Maybe just print a warning that ATSC and Europe don't go together..

**Comment by lelegard** [comment]
Options such as `--atsc` or `--isdb` indicate a standard, typically for PSI/SI. I prefer to add a synthetic option `--usa` which triggers several options, including ATSC and HF region. This is more consistent with similar options such as `--japan` or `--brazil`.

I keep this on the enhancement list.

**Comment by SS-FF** [comment]
I don't care personally. I just thought that it's not ideal for starters when there are too many parameters to set in order to achieve some successful result..
