### ISSUE TITLE
[FEAT] Feature to know when the tsswitch switches to a stream, and if possible info about the previous stream and the next stream

### ISSUE THREAD

**Issue by amit2maha1** [tsduck/tsduck#737]
Problem statement:
* we are trying to use tsswitch to replay live stream recordings
* the live stream recordings are broken into ts chunks based on splice signal
* for example :
  - live stream starts : new livestream ts file starts recording
  - splice out signal generated: the previous livestream file is stopped recording new break ts file starts recording
  - splice in signal generated: previous break file is stopped recording new livestream ts file starts recording
  - and so on....
 * now we have a json file as a playlist for these files
 * when replaying it using tsswitch, we want to manipulate the ad/break duration
 * to do this we need to know when tsswitch switches to the next file

thank you

**Comment by lelegard** [comment]
Hi @amit2maha1 

It is important to understand that tsp and tsswitch don't manage _files_, they manage _plugins_. The two applications just know the plugin API (basically start/stop and a few control functions) but have absolutely no idea of what the plugins are doing. This is precisely the idea of plugins: full independence between the technical management of a plugins pipeline and multiple transport stream processing.

When tsswitch starts a plugin, it has no way to know how, when or if an input plugin will ever stop. An input plugin can run some known finite time (one identified disk file), some unknown finite or infinite time (pipe file or http) or infinitely (dvb, ip, srt and others). Not mentioning of course the possibility of some error forcing an input plugin to stop at any time.

What you request is impossible by design. You need some professional automation tool. TSDuck is just a toolbox for lab activities.

**Comment by amit2maha1** [comment]
> Hi @amit2maha1
> 
> It is important to understand that tsp and tsswitch don't manage _files_, they manage _plugins_. The two applications just know the plugin API (basically start/stop and a few control functions) but have absolutely no idea of what the plugins are doing. This is precisely the idea of plugins: full independence between the technical management of a plugins pipeline and multiple transport stream processing.
> 
> When tsswitch starts a plugin, it has no way to know how, when or if an input plugin will ever stop. An input plugin can run some known finite time (one identified disk file), some unknown finite or infinite time (pipe file or http) or infinitely (dvb, ip, srt and others). Not mentioning of course the possibility of some error forcing an input plugin to stop at any time.
> 
> What you request is impossible by design. You need some professional automation tool. TSDuck is just a toolbox for lab activities.

I see, thank you for your reply. Can you expand on what you mean when you say 'some professional automation tool'. Regardless, thanks again, looks like I will have to think of something else.

**Comment by lelegard** [comment]
> Can you expand on what you mean when you say 'some professional automation tool'. 

I do not have any precise reference to sell. I mean that it seems to me that you are looking for a global playout system, a fully integrated solution. There are several commercial solutions for this. A good starting point would be a catalog of IBC or NAB.

TSDuck is a toolbox, a set of generic hammers and screwdrivers for TV workers 😃 They were designed for lab activities. You may use them to build a production system, but there will be some development. A simple tool such as `tsswitch` is too generic to predict a switch time. With some modest effort, `tsswitch` could be enhanced to signal a switching event, at the moment of the switch. But `tsswitch` will never be able to say _"I will switch in 253.25 seconds"_.

**Comment by amit2maha1** [comment]
> > Can you expand on what you mean when you say 'some professional automation tool'.
> 
> I do not have any precise reference to sell. I mean that it seems to me that you are looking for a global playout system, a fully integrated solution. There are several commercial solutions for this. A good starting point would be a catalog of IBC or NAB.
> 
> TSDuck is a toolbox, a set of generic hammers and screwdrivers for TV workers 😃 They were designed for lab activities. You may use them to build a production system, but there will be some development. A simple tool such as `tsswitch` is too generic to predict a switch time. With some modest effort, `tsswitch` could be enhanced to signal a switching event, at the moment of the switch. But `tsswitch` will never be able to say _"I will switch in 253.25 seconds"_.
I see, I will look into this.

>With some modest effort, tsswitch could be enhanced to signal a switching event, at the moment of the switch

this is exactly what I need, if possible. thank you

**Comment by lelegard** [comment]
I have added two forms of external notifications when `tsswitch` switches input:

1. Launch an external shell command.
2. Send a short JSON message in a UDP datagram (possibly multicast).

In both cases, information is provided on the previous and next input index. See the latest TSDuck user's guide, `tsswitch` command reference in chapter 3, especially the sections entitled "Event notification" and "Event notification options".

Does this meet your expectations?

**Comment by amit2maha1** [comment]
> I have added two forms of external notifications when `tsswitch` switches input:
> 
> 1. Launch an external shell command.
> 2. Send a short JSON message in a UDP datagram (possibly multicast).
> 
> In both cases, information is provided on the previous and next input index. See the latest TSDuck user's guide, `tsswitch` command reference in chapter 3, especially the sections entitled "Event notification" and "Event notification options".
> 
> Does this meet your expectations?

yes, this is exactly what we wanted. thanks a bunch. Also, I have a question
`tsswitch -I fork  'tsp -i -I file C:/path-to-file -P regulate --pcr-synchronous' -I fork  'tsp -i -I file C:/path-to-file -P regulate --pcr-synchronous' -O ip 225.1.2.3:2000`
for this command, the tsswitch is switching automatically regardless of -i (--infinite) option in the tsp. Is this expected behavior or am I doing something wrong?

**Comment by lelegard** [comment]
The `-i` option is not correctly placed.

What you want is telling the `file` plugin to infinitely cycle through all specified files (only one here). In that case, `-i` is an option of the `file` plugin. So, the option must be placed after the plugin name.

The way you use it, _before any plugin_, is an option of the `tsp` command itself, not of any plugin. In `tsp`, `-i` means `--ignore-joint-termination`, something completely unrelated.

So, use `tsp -I file -i ...` instead of `tsp -i -I file ...`.

**Comment by amit2maha1** [comment]
> The `-i` option is not correctly placed.
> 
> What you want is telling the `file` plugin to infinitely cycle through all specified files (only one here). In that case, `-i` is an option of the `file` plugin. So, the option must be placed after the plugin name.
> 
> The way you use it, _before any plugin_, is an option of the `tsp` command itself, not of any plugin. In `tsp`, `-i` means `--ignore-joint-termination`, something completely unrelated.
> 
> So, use `tsp -I file -i ...` instead of `tsp -i -I file ...`.

I see, thank you again.

**Comment by amit2maha1** [comment]
> The `-i` option is not correctly placed.
> 
> What you want is telling the `file` plugin to infinitely cycle through all specified files (only one here). In that case, `-i` is an option of the `file` plugin. So, the option must be placed after the plugin name.
> 
> The way you use it, _before any plugin_, is an option of the `tsp` command itself, not of any plugin. In `tsp`, `-i` means `--ignore-joint-termination`, something completely unrelated.
> 
> So, use `tsp -I file -i ...` instead of `tsp -i -I file ...`.

hello, I will be closing this now. I believe its been resolved.
