### ISSUE TITLE
[BUG] "input plugin pcap not found"

### ISSUE THREAD

**Issue by digitaltvguy** [tsduck/tsduck#748]
#### Bug description:
When attempting to parse a pcap file with tsp an error occurs "input plugin pcap not found"

#### How to reproduce:
Run tsp -I pcap -d <multicast IP:port> <path to output file>

#### Expected behavior:
TS should be extracted

#### Errors and logs:
"input plugin pcap not found"

#### Environment:
 - OS: <macOS>
 - OS version: <11.2.3>
 - TSDuck full version: <3.25-2237>
 - Installation type: <MacOS homebrew>

#### Additional information:
None

**Comment by lelegard** [comment]
Hi @digitaltvguy 

The plugin `pcap` was recently added, after the release of version 3.25. It will be released with version 3.26. In the meantime, I suggest to install [a nightly build version](https://tsduck.io/download/prerelease/) or [rebuild from sources](https://tsduck.io/doxy/building.html).

You did not mention the OS type but version 11.2.3 suggests macOS Big Sur. In that case, just do the following:
~~~
git clone https://github.com/tsduck/tsduck.git
cd tsduck
build/install-prerequisites.sh
make -j10 install
~~~

**Comment by digitaltvguy** [comment]
Thanks for the quick response.  I’ll give the nightly a try.

Do you think someone could update homebrew with a “HEAD” option for nightlys?

All the best,
Chris

From: Thierry Lelegard ***@***.***>
Date: Friday, April 2, 2021 at 8:19 AM
To: tsduck/tsduck ***@***.***>
Cc: Seeger, Chris (NBCUniversal) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [tsduck/tsduck] [BUG] "input plugin pcap not found" (#748)

Hi @digitaltvguy<https://urldefense.com/v3/__https:/github.com/digitaltvguy__;!!PIZeeW5wscynRQ!-FFoEiiCzM0q4Knhu5h7vZn1BPW2I5Chg01P8XZm89KkbVrmR-A0GUwq8MVhKmozXg$>

The plugin pcap was recently added, after the release of version 3.25. It will be released with version 3.26. In the meantime, I suggest to install a nightly build version<https://urldefense.com/v3/__https:/tsduck.io/download/prerelease/__;!!PIZeeW5wscynRQ!-FFoEiiCzM0q4Knhu5h7vZn1BPW2I5Chg01P8XZm89KkbVrmR-A0GUwq8MV-a_fyNg$> or rebuild from sources<https://urldefense.com/v3/__https:/tsduck.io/doxy/building.html__;!!PIZeeW5wscynRQ!-FFoEiiCzM0q4Knhu5h7vZn1BPW2I5Chg01P8XZm89KkbVrmR-A0GUwq8MUwSDtVzQ$>.

You did not mention the OS type but version 11.2.3 suggests macOS Big Sur. In that case, just do the following:

git clone https://github.com/tsduck/tsduck.git<https://urldefense.com/v3/__https:/github.com/tsduck/tsduck.git__;!!PIZeeW5wscynRQ!-FFoEiiCzM0q4Knhu5h7vZn1BPW2I5Chg01P8XZm89KkbVrmR-A0GUwq8MWQ1xiqzA$>

cd tsduck

build/install-prerequisites.sh

make -j10 install

**Comment by lelegard** [comment]
> Do you think someone could update homebrew with a “HEAD” option for nightlys?

I do not know has to manage pre-releases in Homebrew. Since installing TSDuck with Homebrew eventually ends up downloading the source archive and compiling it, I assume that an advanced user willing to install a pre-release can simply rebuild the repo as indicated.

**Comment by digitaltvguy** [comment]
I added a pull request for a “HEAD” option for latest beta releases in Github homebrew formula.

-Chris

From: Thierry Lelegard ***@***.***>
Date: Saturday, April 3, 2021 at 10:27 AM
To: tsduck/tsduck ***@***.***>
Cc: Seeger, Chris (NBCUniversal) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [tsduck/tsduck] [BUG] "input plugin pcap not found" (#748)

Do you think someone could update homebrew with a “HEAD” option for nightlys?

I do not know has to manage pre-releases in Homebrew. Since installing TSDuck with Homebrew eventually ends up downloading the source archive and compiling it, I assume that an advanced user willing to install a pre-release can simply rebuild the repo as indicated.

**Comment by lelegard** [comment]
> I added a pull request for a “HEAD” option for latest beta releases in Github homebrew formula.

It works, thanks!

In order to avoid other users to do the same mistake as me, the correct syntax to install the latest repo is 
~~~
brew install --HEAD tsduck
~~~

And NOT `brew install tsduck --HEAD`.

**Comment by digitaltvguy** [comment]
Thanks for the correction to my syntax

From: Thierry Lelegard ***@***.***>
Date: Sunday, April 4, 2021 at 6:58 AM
To: tsduck/tsduck ***@***.***>
Cc: Seeger, Chris (NBCUniversal) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [tsduck/tsduck] [BUG] "input plugin pcap not found" (#748)

I added a pull request for a “HEAD” option for latest beta releases in Github homebrew formula.

It works, thanks!

In order to avoid other users to do the same mistake as me, the correct syntax to install the latest repo is

brew install --HEAD tsduck

And NOT brew install tsduck --HEAD.

**Comment by rodriguesl6** [comment]
Hi guys,

I tried the pcap to TS command and the result keeps the same: Input pcap not found.

tsp.exe -I Programacao_199_INPUT_%dD%HH%MM%SS -O Programacao_199_INPUT_%dD%HH%MM%SS
* Error: Programacao_199_INPUT_%dD%HH%MM%SS.dll: Impossl localizar o m󤵬o especificado.
* Error: input plugin Programacao_199_INPUT_%dD%HH%MM%SS not found
* Error: Programacao_199_INPUT_%dD%HH%MM%SS.dll: Impossl localizar o m󤵬o especificado.
* Error: output plugin Programacao_199_INPUT_%dD%HH%MM%SS not found

**Comment by lelegard** [comment]
Please do not hijack 3-years old obsolete and close issues, open a new issue for new problems.

As far as I can read your errors, there no "Input pcap not found" message. The message is "input plugin Programacao_199_INPUT_%dD%HH%MM%SS not found", which is quite normal since you typed `-I Programacao_199_INPUT_%dD%HH%MM%SS`. You probably wanted `-I pcap Programacao_199_INPUT_%dD%HH%MM%SS`.

**Comment by rodriguesl6** [comment]
Got it! You are completly right.

The command:
 tsp.exe -I pcap Programacao_199_INPUT_%dD%HH%MM%SS.pcap

Assumes the pcap plugin. The only point that I could't do is save the ouput in a ts file

**Comment by lelegard** [comment]
>  The only point that I could't do is save the ouput in a ts file

Seriously, did you read the user's guide, at least a few examples?

The `file` plugin is used to read/write files: `tsp -I pcap ... -O file out.ts`

This forum is here to help users, not to read the documentation.
