### ISSUE TITLE
[Q] Cannot write pcrextract data into a csv file

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#765]
Hi @lelegard 

I can't succeed to write the `pcrextract` data into a CSV file.

I have tried the below command, which creates the CSV file and displays all the results in the console, but the CSV file remains empty. Any idea?

Command: 
`$ tsp -I ip 225.5.5.5:12345 -P pcrextract --csv -O file test.csv`

Which results in:
```
PID,Packet index in TS,Packet index in PID,Type,Count in PID,Value,Value offset in PID,Offset from PCR
102,131,0,PCR,1,105221825280,0,
102,263,1,PCR,2,105227185536,5360256,
102,395,2,PCR,3,105232545792,10720512,
102,527,3,PCR,4,105237906048,16080768,
102,659,4,PCR,5,105243266304,21441024,
```

The CSV file is created but only contains the following header:
`PID | Packet index in TS | Packet index in PID | Type | Count in PID | Value | Value offset in PID | Offset from PCR`

Am I doing something wrong?

**Comment by lelegard** [comment]
> `$ tsp -I ip 225.5.5.5:12345 -P pcrextract --csv -O file test.csv`

`-O` specifies the output plugin for `tsp`, where output transport stream packets are written. In this command, your `pcrextract ` plugin part is only `-P pcrextract --csv`, displaying on the standard output by default. 

> The CSV file is created but only contains the following header:
> `PID | Packet index in TS | Packet index in PID | Type | Count in PID | Value | Value offset in PID | Offset from PCR`

Given the command above, I don't see how this is possible. The file `test.csv` receives the binary output TS packets, not the expected CSV text.

To get the CSV data in file `test.csv`, the correct command is:
`$ tsp -I ip 225.5.5.5:12345 -P pcrextract --csv -o test.csv -O drop`

Note that you don't even need to specify `--csv` as this is the default output format (as opposed to `--log`).
