### ISSUE TITLE
[BUG] tsp by default "phones home" and creates unexpected files on the users computers

### ISSUE THREAD

**Issue by yaneti** [tsduck/tsduck#783]
Hello @lelegard 

I know you consider this a "feature" but I'd like to disagree, its more of a privacy invasion.
You already have the tsversion utility for anyone needing help in upgrading or checking for new versions on GitHub. 
Doing this by default in tsp is very much crossing the line and absolutely unexpected.

Please drop the unexpected version checks and calls to github from tsp.

Best regards

**Comment by lelegard** [comment]
Concerning the title, TSDuck does not _"phone home"_, it phones GitHub, for what it's worth.
