### ISSUE TITLE
Release Version 3.13-308

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#80]
Hi @lelegard ,

I like to check it the Windows version with HTTP input (Version 3.13-308). Compiling for Linux is trivial. However, for Windows isn't equally easy. So, please, can you release new binaries (almost for Windows in Beta)?

Thank you! :smile:

**Comment by lelegard** [comment]
https://tsduck.io/download/test/TSDuck-Win64-3.13-817.exe
https://tsduck.io/download/test/TSDuck-Win32-3.13-817.exe
https://tsduck.io/download/test/TSDuck-Win64-3.13-817-Portable.zip
https://tsduck.io/download/test/TSDuck-Win32-3.13-817-Portable.zip
