### ISSUE TITLE
[Q] Raspberry Pi TV HAT for DVB-C

### ISSUE THREAD

**Issue by rphanikrishna** [tsduck/tsduck#828]
Did anyone tried the Raspberry Pi TV HAT for DVB-C QAM256, if yes let me know so i can order and try one in India with TSDuck.

**Comment by lelegard** [comment]
One user reported a successful use of the TV HAT [here](https://github.com/tsduck/tsduck/issues/24#issuecomment-786284473) but it was with DVB-T and T2. The [TV HAT product description](https://www.raspberrypi.org/app/uploads/2018/10/Raspberry-Pi-TV-HAT-Product-Brief.pdf) only mentions "Supported TV standards: DVB-T2, DVB-T".
