### ISSUE TITLE
[FEAT] SRT  - specify input or output interface

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#836]
#### Is your feature request related to a problem?
Specifically, when working in caller mode, it would be great to be able to specify the output interface. Same as with IP output plugin.
In general it would be good to do it for both listener and caller mode

#### Proposed solution:
it should be possible to specify the output interface when working in caller  or listener mode, like for IP input or output plugin

**Comment by lelegard** [comment]
Hi @enricovittorini,

The option `--local-interface` has been added to specify the outgoing interface in caller mode. This option shall not be used in listener or rendezvous mode since the local interface and port are already specified.
