### ISSUE TITLE
[Q] nodejs spawn and PSI plucing

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#846]
hello @lelegard ,
i have a question:

I am suing a nodejs app to run tsp by creating a childporcess ([spawn](https://nodejs.org/api/child_process.html#child_process_event_exit)).

i would like to use the --event-code option of the psi plugin to get an event from the plugin.

do you know if this is doable with nodejs and spawn?

thanks

**Comment by lelegard** [comment]
Plugin events are synchronous calls inside the virtual memory space of the process which executes the plugins. So, they can only be used by developers who write C++, Java or Python applications using the class `TSProcessor` (available in the three languages). They are useless with the `tsp` application.
