### ISSUE TITLE
HTTP input on Windows caching issue

### ISSUE THREAD

**Issue by rezna11** [tsduck/tsduck#88]
Would it be possible to change WinINet implementation in TSDuck to make it possible to turn off or limit caching? When running TSDuck with HTTP input, I noticed free disk space going down, then I found a very large mpeg file (see attached screenshot). I think it's TSDuck doing this.
![inetcache](https://user-images.githubusercontent.com/20435164/42408020-e4ccc074-81c6-11e8-9957-db3d1426a8e3.PNG)

**Comment by rezna11** [comment]
by the way, I tried adding

```
INTERNET_FLAG_DONT_CACHE |
INTERNET_FLAG_NO_CACHE_WRITE |
```

in \src\libtsduck\windows\tsWebRequestGuts.cpp

and it seems to solve the problem

**Comment by lars18th** [comment]
:open_mouth: :open_mouth: :open_mouth: 
This is very embarrassing behavior!
Neither processing tool should generate temporary files. And much less ring buffer stream files. That would collapse the system!

So, please @lelegard review the code. If @rezna11 has targeted this problem and it's true, then fix it.

Thank you all for this impresive project!

**Comment by lelegard** [comment]
Integrated. 

`INTERNET_FLAG_NO_CACHE_WRITE` is sufficient. The other value is the same (and no longer documented).
Excerpt from WinInet.h :

~~~
#define INTERNET_FLAG_NO_CACHE_WRITE    0x04000000  // don't write this item to the cache
#define INTERNET_FLAG_DONT_CACHE        INTERNET_FLAG_NO_CACHE_WRITE
~~~

**Comment by rezna11** [comment]
thanks for a very fast fix, looks good!
