### ISSUE TITLE
[Q] NSTV CAS type is not showing 

### ISSUE THREAD

**Issue by getpartha1** [tsduck/tsduck#881]
In the  tsp report NSTV CAS type is not showing.
Can i add it myself or its required to be added in to the code.
~~~
|-----------------------------------------------------------------------------|
|  Global PID                Transport:                Discontinuities:       |
|  Bitrate: ... 264,223 b/s  Packets: ........ 20,214  Expected: ......... 0  |
|  Access: .......... Clear  Adapt.F.: ............ 0  Unexpect: ......... 0  |
|                            Duplicated: .......... 0  Sections:              |
|                            PCR: ................. 0  Unit start: ... 8,864  |
|=============================================================================|
|  PID: 0x005C (92)                                     unknown (0x4A02) EMM  |
|-----------------------------------------------------------------------------|
~~~
i am new user to tsduck.

Thanks in advance.

Regards,
Partha

**Comment by lelegard** [comment]
Hi @getpartha1 

It looks like this is not an official CA system id. If you look at the [allocated CA system id table](https://www.dvbservices.com/identifiers/ca_system_id?page=4), `0x4A02` is an unallocated value. I do not know what NSTC CAS is but it looks like they used a non-official unallocated value.

Anyway, if your just need to display a name for this CA system id, there is no need to change the code. All names are in configuration files. For CA system ids, look at `/usr/share/tsduck/tsduck.names` (in `C:\Program Files\TSDuck\bin` on Windows):
~~~
...
[CASystemId]
Bits = 16
0x0001 = IPDC SPP Open Security Framework Generic Roaming
0x0002 = 18Crypt
...
0x4900-0x49FF = CrytoWorks China (Irdeto)
0x4A10-0x4A1F = Easycas
0x4A20-0x4A2F = AlphaCrypt
...
~~~
You may add new values. Note that the file is overwritten each time TSDuck is updated.

If you work for or with NSTV CAS, you may develop a private TSDuck extension to analyse the structure of CA descriptors, private tables, ECM or EMM (at least any clear information). See the directory `sample/sample-extension` in TSDuck source tree.

**Comment by getpartha1** [comment]
Thank You Very Much Mr.Lelegard.
