### ISSUE TITLE
[Q]  SRT listener stats and other info

### ISSUE THREAD

**Issue by themoog** [tsduck/tsduck#884]
Is it possible to log any info when in SRT listenmode? (retransmits, dropped packets, peer buffer latency etc?)

Thanks in advance

Neil

**Comment by George-** [comment]
Hi @lelegard, would the developer of the SRT plugin consider adding JSON stats flag like other TS Duck plugins to provide the statistics in a standard format to be used in other applications? 
Thanks, 
George

**Comment by lelegard** [comment]
> consider adding JSON stats

See #940
