### ISSUE TITLE
[FEAT] Splicemonitor with “Normalized” reports

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#889]
Hello @lelegard 

In order to automate SCTE-35 Monitoring/Analysis in scripts, I was wondering if it is possible to make the `splicemonitor` plugin evolve, by providing either XML or JSON report format (I'm not fussy on that one) using the `--normalized` option?

**Comment by lelegard** [comment]
Hi,

The options `--json` and `--json-line` have been added (same principle as plugins `tables` or `psi` for instance).

**Comment by moving-digital** [comment]
Thank you so much !
