### ISSUE TITLE
[BUG] SpliceInject plugin not generating the expected splice duration if CUE-IN preceded by more than one CUE-OUT

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#910]
Hi @lelegard , I would need your help for the below bug:

#### Bug description:
- Working use-case: When starting TSP process, injecting a CUE-OUT then a CUE-IN, TSP/Spliceinject plugin will generate the expected break duration such as duration = delta between CUE-IN and CUE-OUT.
- Failing use-case: However, when starting TSP process, injecting a first CUE-OUT, then a second CUE-OUT, then a CUE-IN, TSP/Spliceinject plugin will not behave correctly and will simply not be able to generate the expected splice duration which should be the delta between the CUE-IN and the last CUE-OUT received.

Note 1: Not all Content Provider will always be sending a CUE-OUT followed by a CUE-IN, in order to create a CUE pair able to create a proper ad break. Some Content Provider may be sending many CUE-OUT, before sending a CUE-IN.
Note 2: Or, some taker/service provider may not be receiving correctly all the CUE-OUT/CUE-IN pair from the Content Provider. For instance, a CUE-IN may be missed for some reason (the CP forgets to send it, or the Service provider did not receive it for some reason). In this case, we will also end up in a situation where the CUE-OUT/IN pair will be broken, then TSP spliceinject plugin will not be able to recover on its own.

#### How to reproduce:
- Working use-case: Start TSP process. Inject a CUE-OUT then a CUE-IN. The break duration shall be = delta between CUE-IN and CUE-OUT.
- Failing use-case: Start TSP process. Inject a first CUE-OUT, then a second one few seconds later. Finally, inject a CUE-IN. The break duration between the second CUE-OUT and the CUE-IN will not be generated correctly.

#### Expected behavior:
When injecting many CUE-OUT without any CUE-IN, and suddenly injecting a CUE-IN, this must result in creating an ad break with the duration being equal to the delta between the CUE-IN and the last CUE-OUT sent.

#### Errors and logs:
No errors. But logs with `verbose` and `debug` are shared below in the second post.

#### Environment:
 - OS: Linux
 - OS version: CentOS 7.9
 - TSDuck full version: 3.30-2663
 - Installation type: official binary 

#### Additional information:
Once TSP plugin is "stuck" in this situation whereby it is not able to generate the right splice duration anymore, I got two options to fix the issue. Needless to say that none of them are acceptable and they can't be considered a workaround at all:
1) Hard one: kill TSP process, and restart a new one
2) Softer one but still not acceptable: I get to send many CUE-IN (2, 3 or 4) then it will "unlock" TSP, meaning that the next time I send one and only one CUE-OUT followed by a CUE-IN, the right duration will be computed. This is also not acceptable since we are talking about live events...

**Comment by moving-digital** [comment]
Hi @lelegard 

Some more info from my side that shall be pretty handy in order to troubleshoot:

Working test: 2 cues sent only
1. One CUE-OUT
2. One CUE-IN

![image](https://user-images.githubusercontent.com/81666507/145912862-0af76590-afa9-4ca1-a153-a2d47434432f.png)

Failing test: 3 cues sent
1. One CUE-OUT
2. Another CUE-OUT
3. One CUE-IN

![image](https://user-images.githubusercontent.com/81666507/145913092-fca9ab08-8dcc-4974-bf56-427feb28fedb.png)

The two TS captures can be downloaded here:
https://we.tl/t-q9V4NRMYCO

**Comment by lelegard** [comment]
Hi @moving-digital 

I am afraid I do not understand the actual nature of the problem. Is this is a problem with the `spliceinject` or `splicemonitor` plugin? Which duration are you referring to? The splice_insert commands are immediate, so there is no duration involved.

**Comment by moving-digital** [comment]
> Hi @moving-digital
> 
> I am afraid I do not understand the actual nature of the problem. Is this is a problem with the `spliceinject` or `splicemonitor` plugin? Which duration are you referring to? The splice_insert commands are immediate, so there is no duration involved.

Hi @lelegard, the problem is according to me with `spliceinject`.

When sending a cue-out (start break), then a cue-in (stop break) later, this should basically create a single break with a duration = delta from CUE-IN - CUE-OUT.

However, there is an issue when two cue-out are sent first, followed by one cue-in. In this case, CMA is not able to get the proper break information, I believe due to an issue in spliceinject.

**Comment by lelegard** [comment]
If the problem is that the CMA analyzer is not able to compute a duration, then it seems a problem in the CMA analyzer, isn't it?

All your commands are immediate. So, `spliceinject` has little added value, it just injects the command immediately. That's all. There is no duration information in the splice table. If the analyzer is lost when it get two "splice out" and one "splice in" later, this seems a problem of the analyzer.
