### ISSUE TITLE
[Q] Add libsrt to pre-requisite script for Alpine Linux

### ISSUE THREAD

**Issue by George-** [tsduck/tsduck#926]
Please can libsrt/libsrt-dev be added to the install-prerequisite.sh script for Alpine distributions? 

I modified the script locally to include these packages and this worked with the latest version of Alpine.

**Comment by lelegard** [comment]
Done. Thanks for the update. SRT was not available on Alpine when I wrote this.

**Comment by George-** [comment]
Many thanks!
