### ISSUE TITLE
[FEAT] JSON standard output for SRT plugin statistics 

### ISSUE THREAD

**Issue by George-** [tsduck/tsduck#940]
#### Is your feature request related to a problem?
Consuming the statistics using the flags available on the SRT input is difficult in other applications or scripts, e.g. python

#### Proposed solution:
Add a —json flag to the SRT plug-in for TSDuck similar to the flag provided on other plugins. If possible make this available for all stats, including the separate bitrate reporting interval stats.

**Comment by lelegard** [comment]
The following option has been added to the `srt` input and output plugins:
~~~
--json-line[='prefix']
    With --statistics-interval or --final-statistics, report the statistics
    as one single line in JSON format. The optional string parameter
    specifies a prefix to prepend on the log line before the JSON text to
    locate the appropriate line in the logs.
~~~

**Comment by George-** [comment]
That works perfectly, thanks @lelegard 👍
