### ISSUE TITLE
[FEAT] splicemonitor plugin: option to filter/disable/discard "splice_null" and "bandwidth_reservation"

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#954]
Hello @lelegard 

#### Is your feature request related to a problem?
The feature request is related to an improvement of `splicemonitor` plugin.
Not a problem, but performances issue due to `splice_null` command inserted every 1 second in the TS to monitor, causing throttling for the CPU receiving too much information.

#### Proposed solution:
Would it be possible to add an option to filter/disable/discard "splice_null" and "bandwidth_reservation" ?
The idea would be for splicemonitor to only output logs about the "relevant" splices (insert, schedule, time signal), but not the null ones.

#### Alternatives:
No alternative.

**Comment by lelegard** [comment]
Hi @moving-digital 

The option `--select-commands` has been added.

Example: to display insert, schedule, time signal only, use `--select-commands 4-6`.

**Comment by moving-digital** [comment]
So fast ! Thanks a lot, @lelegard  !
