### ISSUE TITLE
svrename: missing ProviderName

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#97]
Hi @lelegard 

In the plugin `svrename` I miss the parameter to change the ProviderName (`--provider-name`).

I need it to prapare the SPTS to the muxer (`merge`).
Please, if you think it has sense, can you add support for it?
Thank you!

**Comment by lelegard** [comment]
Will be added. In the meantime, you can do that using plugin `sdt`.

**Comment by lars18th** [comment]
Ok, it's true.

However, until now I'm doing it already with `P sdt --cleanup-private-descriptors --provider "test"` after the `-P svrename`. But that today I noticed that with the last commit the provider name doesn't change! And I don't know why!

For this reason I ask to include in the `svrename`. But in fact, now I feel isn't needed as `sdt` does it. But the problem is a possible bug. Can you check it, please?

**Comment by lelegard** [comment]
~~~
 tsp -P sdt --help
...
  -p value
  --provider value
      Specify a new provider name for the added or modified service.
      For new services, the default is an empty string.
...
  -s value
  --service-id value
      Add a new service or modify the existing service with the specified
      service-id.
~~~

You need to specify which service you want to modify in the SDT. A transport stream is multi-service in essence. An SPTS is just a specific case of TS.

**Comment by lars18th** [comment]
Yeah! Thank you! :+1: 
I missed the `-s` value for selecting the program with the `sdt` plugin, so: `-P sdt -s 1 --cleanup-private-descriptors --provider "test"` really works.

**Comment by lelegard** [comment]
I have added `--provider` in `tsrename`. It was trivial.
Wait for next push.
Closing this one.
