### ISSUE TITLE
[Q] "fork (packet processing)" for output stream duplication: does it inherit the Main TSP options and plugins?

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#971]
Hi @lelegard 

I'm currently playing with `fork (packet processing)` plugin. I'm using it to duplicate an output stream.

Basically, I got one TS input and I need to duplicate the output few times (different network interfaces, but same TSP parameters/options).

My questions are the following:
1. If the Main TSP is already using specific options (e.g. --bitrate 1000000 --initial-input-packets 7 --max-input-packets 7 --max-flushed-packets 7), do we also need to specify them in the forked process or does it automatically inherit the main TSP options?
2. If the Main TSP is already using specific plugins such as `-P pcrbitrate` and `-P continuity --fix` do we need to redeclare them in the forked process, or does it automatically inherit the main TSP plugins?

**Comment by lelegard** [comment]
Hi @moving-digital 

The `fork` plugin creates a process and sends the binary TS, as seen at this point of the chain, to the forked process. That's all. The forked command can be `tsp` or anything else. There is no specific assumption that the forked process is `tsp`. Neither there is any out-of-band communication mechanism to transmit some specific tsp-to-tsp configuration.

The plugin `pcrbitrate` only re-evaluates the bitrate at this point in the chain and propagates it to the next plugin. This information is internal to `tsp` and consequently not passed to the forked process.

The plugin `-P continuity --fix` modifies the packets and fixes any continuity error. If this plugin is _before_ `fork` in the chain, then the modified packets are passed to the forked process and there is no need to do it again in the forked process, the potential CC errors were already fixed upstream.
