### ISSUE TITLE
[FEAT] Use custom thread names for plugins in tsp

### ISSUE THREAD

**Issue by basicmaster** [tsduck/tsduck#976]
#### Is your feature request related to a problem?
When `tsp` is used with a larger processing chain, it can be desirable to compare how much CPU power the different plugins (i.e. threads) consume.

Currently the threads of a single `tsp` instance cannot be distinguished (`htop` in tree mode, "Show custom thread names" enabled):

![grafik](https://user-images.githubusercontent.com/7103991/163635557-74e18f8d-1d77-43da-946d-e22f27c89b8e.png)

#### Proposed solution:
On Linux, a custom thread name can be set for a thread. So for example in `ts::tsp::InputExecutor::main()`, `ts::tsp::ProcessorExecutor::main()` and `ts::tsp::OutputExecutor::main()` the following call could be added to set the applicable thread name (requires to `#include <sys/prctl.h>`):

```
prctl(PR_SET_NAME, pluginName().toUTF8().c_str());
```

In the above example, this results in the following `htop` output:
![grafik](https://user-images.githubusercontent.com/7103991/163635565-befe212e-8fcf-4ec1-87f1-c1dae3524fde.png)

#### Alternatives:
(none)

#### Additional information:
https://man7.org/linux/man-pages/man2/prctl.2.html

**Comment by lelegard** [comment]
Hi @basicmaster

Good idea, thanks.
Done. With equivalence on macOS and Windows as well.

**Comment by basicmaster** [comment]
Great, works as expected. Thank you for adding this feature!
