### ISSUE TITLE
[Q] Insert an audio stream in a TS

### ISSUE THREAD

**Issue by Litrona** [tsduck/tsduck#992]
I want to to replace an audio ES with another one, with exactly the same CBR, so it will fit in the same space.
How can I do that with tsp ?
Thanks in advance

**Comment by lelegard** [comment]
Hi @Litrona 

There is no easy way. As mentioned hundredths of times here, muxing audio/video needs a MUX and TSDuck is not a MUX.

If you have exactly identical CBR audio streams, this may be easier than a full MUX but you still need to synchronize the PTS/DTS of the injected audio stream with the PCR of the service. This would be relatively easy with a specialized plugin, yet to be developed...
